# Generated by Django 5.1.15 on 2026-02-14 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0004_sla_escalationrule_caseslastatus_slabreach"),
        ("contacts", "0007_contacttag_contacttagassignment"),
        (
            "portal",
            "0005_rename_crm_portal__contact_f3d8b4_idx_crm_portal__contact_e9dcdf_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatDepartment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "auto_assign",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically assign chats to available agents",
                        verbose_name="auto assign",
                    ),
                ),
                (
                    "max_concurrent_chats",
                    models.PositiveIntegerField(
                        default=5, verbose_name="max concurrent chats per agent"
                    ),
                ),
                (
                    "offline_message",
                    models.TextField(
                        default="We're currently offline. Please leave a message and we'll get back to you.",
                        verbose_name="offline message",
                    ),
                ),
                (
                    "collect_email_offline",
                    models.BooleanField(
                        default=True, verbose_name="collect email when offline"
                    ),
                ),
            ],
            options={
                "verbose_name": "department",
                "verbose_name_plural": "departments",
                "db_table": "livechat_departments",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ChatWidgetSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_color",
                    models.CharField(
                        default="#3b82f6", max_length=20, verbose_name="primary color"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("bottom-right", "Bottom Right"),
                            ("bottom-left", "Bottom Left"),
                        ],
                        default="bottom-right",
                        max_length=20,
                        verbose_name="position",
                    ),
                ),
                (
                    "button_icon",
                    models.CharField(
                        default="chat", max_length=50, verbose_name="button icon"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="Support", max_length=100, verbose_name="company name"
                    ),
                ),
                (
                    "welcome_message",
                    models.TextField(
                        default="Hi there! How can we help you today?",
                        verbose_name="welcome message",
                    ),
                ),
                (
                    "away_message",
                    models.TextField(
                        default="We're not available right now. Please leave a message.",
                        verbose_name="away message",
                    ),
                ),
                (
                    "require_name",
                    models.BooleanField(default=True, verbose_name="require name"),
                ),
                (
                    "require_email",
                    models.BooleanField(default=True, verbose_name="require email"),
                ),
                (
                    "require_phone",
                    models.BooleanField(default=False, verbose_name="require phone"),
                ),
                (
                    "require_department",
                    models.BooleanField(
                        default=False, verbose_name="require department selection"
                    ),
                ),
                (
                    "auto_popup",
                    models.BooleanField(default=False, verbose_name="auto popup"),
                ),
                (
                    "auto_popup_delay",
                    models.PositiveIntegerField(
                        default=30, verbose_name="auto popup delay (seconds)"
                    ),
                ),
                (
                    "play_sound",
                    models.BooleanField(
                        default=True, verbose_name="play sound on new message"
                    ),
                ),
                (
                    "show_agent_photo",
                    models.BooleanField(default=True, verbose_name="show agent photo"),
                ),
                (
                    "show_typing_indicator",
                    models.BooleanField(
                        default=True, verbose_name="show typing indicator"
                    ),
                ),
                (
                    "use_operating_hours",
                    models.BooleanField(
                        default=False, verbose_name="use operating hours"
                    ),
                ),
                (
                    "operating_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Operating hours by day of week",
                        verbose_name="operating hours",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", max_length=50, verbose_name="timezone"
                    ),
                ),
                (
                    "file_upload_enabled",
                    models.BooleanField(
                        default=True, verbose_name="enable file uploads"
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.PositiveIntegerField(
                        default=10, verbose_name="max file size (MB)"
                    ),
                ),
                (
                    "allowed_file_types",
                    models.JSONField(
                        blank=True, default=list, verbose_name="allowed file types"
                    ),
                ),
                (
                    "enable_rating",
                    models.BooleanField(
                        default=True, verbose_name="enable chat rating"
                    ),
                ),
                (
                    "rating_prompt",
                    models.CharField(
                        default="How was your experience?",
                        max_length=200,
                        verbose_name="rating prompt",
                    ),
                ),
                (
                    "offer_transcript",
                    models.BooleanField(default=True, verbose_name="offer transcript"),
                ),
            ],
            options={
                "verbose_name": "widget settings",
                "verbose_name_plural": "widget settings",
                "db_table": "livechat_widget_settings",
            },
        ),
        migrations.CreateModel(
            name="ChatAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_available",
                    models.BooleanField(default=False, verbose_name="available"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("away", "Away"),
                            ("busy", "Busy"),
                            ("offline", "Offline"),
                        ],
                        default="offline",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_message",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="status message",
                    ),
                ),
                (
                    "max_concurrent_chats",
                    models.PositiveIntegerField(
                        default=5, verbose_name="max concurrent chats"
                    ),
                ),
                (
                    "current_chat_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="current chat count"
                    ),
                ),
                ("total_chats_handled", models.PositiveIntegerField(default=0)),
                ("avg_response_time", models.DurationField(blank=True, null=True)),
                ("avg_rating", models.FloatField(blank=True, null=True)),
                (
                    "sound_enabled",
                    models.BooleanField(
                        default=True, verbose_name="sound notifications"
                    ),
                ),
                (
                    "desktop_notifications",
                    models.BooleanField(
                        default=True, verbose_name="desktop notifications"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last seen"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_agent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="agents",
                        to="live_chat.chatdepartment",
                        verbose_name="departments",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat agent",
                "verbose_name_plural": "chat agents",
                "db_table": "livechat_agents",
            },
        ),
        migrations.CreateModel(
            name="CannedResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                (
                    "shortcut",
                    models.CharField(
                        help_text="Type /shortcut to use this response",
                        max_length=50,
                        unique=True,
                        verbose_name="shortcut",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "is_global",
                    models.BooleanField(
                        default=False,
                        help_text="Available to all departments",
                        verbose_name="global",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, verbose_name="usage count"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canned_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canned_responses",
                        to="live_chat.chatdepartment",
                        verbose_name="department",
                    ),
                ),
            ],
            options={
                "verbose_name": "canned response",
                "verbose_name_plural": "canned responses",
                "db_table": "livechat_canned_responses",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="session ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("active", "Active"),
                            ("on_hold", "On Hold"),
                            ("closed", "Closed"),
                            ("missed", "Missed"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("widget", "Chat Widget"),
                            ("portal", "Customer Portal"),
                            ("internal", "Internal"),
                        ],
                        default="widget",
                        max_length=20,
                        verbose_name="source",
                    ),
                ),
                (
                    "visitor_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="visitor name"
                    ),
                ),
                (
                    "visitor_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="visitor email"
                    ),
                ),
                (
                    "visitor_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="visitor phone"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="started at"),
                ),
                (
                    "first_response_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="first response at"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ended at"
                    ),
                ),
                (
                    "wait_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="wait time"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="subject"
                    ),
                ),
                (
                    "initial_message",
                    models.TextField(blank=True, verbose_name="initial message"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "page_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="page URL"
                    ),
                ),
                (
                    "referrer",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="referrer"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="tags"),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="custom fields"
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1-5 stars",
                        null=True,
                        verbose_name="rating",
                    ),
                ),
                (
                    "rating_comment",
                    models.TextField(blank=True, verbose_name="rating comment"),
                ),
                (
                    "transcript_sent",
                    models.BooleanField(default=False, verbose_name="transcript sent"),
                ),
                ("transcript_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_sessions",
                        to="live_chat.chatagent",
                        verbose_name="assigned agent",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to="contacts.contact",
                        verbose_name="contact",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="live_chat.chatdepartment",
                        verbose_name="department",
                    ),
                ),
                (
                    "portal_access",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to="portal.clientportalaccess",
                        verbose_name="portal access",
                    ),
                ),
                (
                    "previous_agents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="previous_sessions",
                        to="live_chat.chatagent",
                        verbose_name="previous agents",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat session",
                "verbose_name_plural": "chat sessions",
                "db_table": "livechat_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("file", "File"),
                            ("image", "Image"),
                            ("system", "System"),
                            ("note", "Internal Note"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="message type",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("visitor", "Visitor"),
                            ("agent", "Agent"),
                            ("system", "System"),
                            ("bot", "Bot"),
                        ],
                        max_length=20,
                        verbose_name="sender type",
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="sender name"
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="livechat/attachments/%Y/%m/",
                        verbose_name="file",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="file name"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="file size"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="file type"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="read at"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="delivered at"
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(default=False, verbose_name="internal note"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="live_chat.chatagent",
                        verbose_name="agent",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="live_chat.chatsession",
                        verbose_name="session",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat message",
                "verbose_name_plural": "chat messages",
                "db_table": "livechat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfflineMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="phone"),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "page_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="page URL"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="read at"),
                ),
                (
                    "is_responded",
                    models.BooleanField(default=False, verbose_name="responded"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="responded at"
                    ),
                ),
                (
                    "converted_to_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="from_offline_messages",
                        to="cases.taxcase",
                        verbose_name="converted to case",
                    ),
                ),
                (
                    "converted_to_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="from_offline_messages",
                        to="contacts.contact",
                        verbose_name="converted to contact",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offline_messages",
                        to="live_chat.chatdepartment",
                        verbose_name="department",
                    ),
                ),
                (
                    "read_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="read_offline_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="read by",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responded_offline_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "offline message",
                "verbose_name_plural": "offline messages",
                "db_table": "livechat_offline_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["status", "department"], name="livechat_se_status_e4abc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["assigned_agent", "status"],
                name="livechat_se_assigne_8d94f6_idx",
            ),
        ),
    ]
