# Generated by Django 5.1.15 on 2026-02-05 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_hours', '0001_initial'),
        ('corporations', '0002_corporation_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='annual_revenue_range',
            field=models.CharField(blank=True, choices=[('under_100k', 'Under $100,000'), ('100k_500k', '$100,000 - $500,000'), ('500k_1m', '$500,000 - $1,000,000'), ('1m_5m', '$1,000,000 - $5,000,000'), ('5m_10m', '$5,000,000 - $10,000,000'), ('10m_25m', '$10,000,000 - $25,000,000'), ('25m_50m', '$25,000,000 - $50,000,000'), ('50m_100m', '$50,000,000 - $100,000,000'), ('over_100m', 'Over $100,000,000')], default='', max_length=20, verbose_name='annual revenue range'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='billing_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='billing city'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='billing_country',
            field=models.CharField(blank=True, default='United States', max_length=100, verbose_name='billing country'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='billing_po_box',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='billing PO box'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='billing_state',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='billing state'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='billing_street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='billing street'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='billing_zip',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='billing ZIP code'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='email_domain',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='email domain'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='email_opt_in',
            field=models.CharField(choices=[('single_opt_in', 'Single opt-in (user)'), ('double_opt_in', 'Double opt-in'), ('opt_out', 'Opt-out'), ('not_set', 'Not set')], default='single_opt_in', max_length=20, verbose_name='email opt-in'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='employees',
            field=models.PositiveIntegerField(blank=True, help_text='Number of employees', null=True, verbose_name='employees'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='facebook_url',
            field=models.URLField(blank=True, default='', verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='corporations/images/', verbose_name='organization image'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='member_of',
            field=models.ForeignKey(blank=True, help_text='Parent organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='corporations.corporation', verbose_name='member of'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='notify_owner',
            field=models.BooleanField(default=False, verbose_name='notify owner'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='organization_status',
            field=models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='cold', max_length=10, verbose_name='organization status'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='organization_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('customer', 'Customer'), ('partner', 'Partner'), ('reseller', 'Reseller'), ('competitor', 'Competitor'), ('investor', 'Investor'), ('press', 'Press'), ('prospect', 'Prospect'), ('other', 'Other')], db_index=True, default='lead', max_length=20, verbose_name='organization type'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='ownership',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ownership'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='region',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('northeast', 'Northeast'), ('northwest', 'Northwest'), ('southeast', 'Southeast'), ('southwest', 'Southwest'), ('central', 'Central'), ('international', 'International')], default='', max_length=20, verbose_name='region'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='secondary_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='secondary email'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='secondary_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='secondary phone'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='shipping_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='shipping city'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='shipping_country',
            field=models.CharField(blank=True, default='United States', max_length=100, verbose_name='shipping country'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='shipping_po_box',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='shipping PO box'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='shipping_state',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='shipping state'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='shipping_street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='shipping street'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='shipping_zip',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='shipping ZIP code'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='sic_code',
            field=models.CharField(blank=True, default='', help_text='Standard Industrial Classification code', max_length=20, verbose_name='SIC code'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='sla',
            field=models.ForeignKey(blank=True, help_text='Service Level Agreement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporations', to='business_hours.businesshours', verbose_name='SLA'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='sms_opt_in',
            field=models.CharField(choices=[('single_opt_in', 'Single opt-in (user)'), ('double_opt_in', 'Double opt-in'), ('opt_out', 'Opt-out'), ('not_set', 'Not set')], default='single_opt_in', max_length=20, verbose_name='SMS opt-in'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='ticker_symbol',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ticker symbol'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='timezone'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='twitter_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Twitter username'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='fax'),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='phone'),
        ),
    ]
