# Generated by Django 5.1.15 on 2026-02-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporations", "0003_add_vtiger_organization_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporation",
            name="account_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Unique account identifier (e.g., ACC-0001)",
                max_length=50,
                verbose_name="account number",
            ),
        ),
    ]
