# Generated by Django 5.1.15 on 2026-02-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corporations", "0004_add_account_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corporation",
            name="account_number",
        ),
    ]
