# Generated by Django 5.1.15 on 2026-02-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporations", "0008_corporation_idx_corp_status_assigned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporation",
            name="related_corporations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other corporations related to this one",
                to="corporations.corporation",
                verbose_name="related corporations",
            ),
        ),
    ]
