# Generated by Django 5.1.15 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agent", "0001_initial"),
    ]

    operations = [
        # Add backup automation fields to AgentConfiguration
        migrations.AddField(
            model_name="agentconfiguration",
            name="auto_backup_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable AI-powered automatic backups",
            ),
        ),
        migrations.AddField(
            model_name="agentconfiguration",
            name="backup_schedule_hour",
            field=models.PositiveIntegerField(
                default=23,
                help_text="Hour of day to run backup analysis (0-23)",
            ),
        ),
        migrations.AddField(
            model_name="agentconfiguration",
            name="backup_include_media",
            field=models.BooleanField(
                default=True,
                help_text="Include media files in automated backups",
            ),
        ),
        migrations.AddField(
            model_name="agentconfiguration",
            name="backup_contacts_threshold",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Number of contact changes to trigger backup consideration",
            ),
        ),
        migrations.AddField(
            model_name="agentconfiguration",
            name="backup_cases_threshold",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Number of case changes to trigger backup consideration",
            ),
        ),
        migrations.AddField(
            model_name="agentconfiguration",
            name="backup_documents_threshold",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Number of new documents to trigger backup consideration",
            ),
        ),
        migrations.AddField(
            model_name="agentconfiguration",
            name="backup_corporations_threshold",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Number of corporation changes to trigger backup consideration",
            ),
        ),
        migrations.AddField(
            model_name="agentconfiguration",
            name="backup_emails_threshold",
            field=models.PositiveIntegerField(
                default=50,
                help_text="Number of emails to trigger backup consideration",
            ),
        ),
        migrations.AddField(
            model_name="agentconfiguration",
            name="backup_activity_threshold",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Number of API activities to trigger backup consideration",
            ),
        ),
        migrations.AddField(
            model_name="agentconfiguration",
            name="backup_days_since_last",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Force backup if this many days have passed since last backup",
            ),
        ),
        migrations.AddField(
            model_name="agentconfiguration",
            name="backup_retention_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Auto-delete automated backups older than this many days",
            ),
        ),
        # Add BACKUP_CREATED to ActionType choices
        migrations.AlterField(
            model_name="agentaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("email_note", "Created note from email"),
                    ("appt_reminder", "Sent appointment reminder"),
                    ("task_reminder", "Sent task reminder"),
                    ("task_escalated", "Escalated overdue task"),
                    ("insight", "Generated business insight"),
                    ("recommendation", "Made recommendation"),
                    ("email_sent", "Sent email"),
                    ("task_created", "Created task"),
                    ("backup_created", "Created automated backup"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
