from django.core.management.base import BaseCommand

from apps.module_config.models import CRMModule, Picklist, PicklistValue

MODULE_SEED = [
    {
        "name": "contacts",
        "label": "Contact",
        "label_plural": "Contacts",
        "icon": "Users",
        "description": "Individual contacts and leads",
        "sort_order": 1,
        "number_prefix": "CT",
        "number_format": "{prefix}-{year}-{seq:04d}",
        "number_reset_period": "yearly",
    },
    {
        "name": "corporations",
        "label": "Corporation",
        "label_plural": "Corporations",
        "icon": "Building",
        "description": "Business entities and organizations",
        "sort_order": 2,
        "number_prefix": "CO",
        "number_format": "{prefix}-{year}-{seq:04d}",
        "number_reset_period": "yearly",
    },
    {
        "name": "cases",
        "label": "Tax Case",
        "label_plural": "Tax Cases",
        "icon": "Briefcase",
        "description": "Tax engagements and filings",
        "sort_order": 3,
        "number_prefix": "TC",
        "number_format": "{prefix}-{year}-{seq:04d}",
        "number_reset_period": "yearly",
    },
    {
        "name": "quotes",
        "label": "Quote",
        "label_plural": "Quotes",
        "icon": "FileText",
        "description": "Service proposals and fee estimates",
        "sort_order": 4,
        "number_prefix": "QT",
        "number_format": "{prefix}-{YYYYMMDD}-{seq:03d}",
        "number_reset_period": "yearly",
    },
    {
        "name": "appointments",
        "label": "Appointment",
        "label_plural": "Appointments",
        "icon": "Calendar",
        "description": "Scheduled meetings and consultations",
        "sort_order": 5,
        "number_prefix": "AP",
        "number_format": "",
        "number_reset_period": "never",
    },
    {
        "name": "documents",
        "label": "Document",
        "label_plural": "Documents",
        "icon": "File",
        "description": "Files and document management",
        "sort_order": 6,
        "number_prefix": "DC",
        "number_format": "",
        "number_reset_period": "never",
    },
    {
        "name": "tasks",
        "label": "Task",
        "label_plural": "Tasks",
        "icon": "CheckSquare",
        "description": "Internal tasks and to-dos",
        "sort_order": 7,
        "number_prefix": "TK",
        "number_format": "",
        "number_reset_period": "never",
    },
    {
        "name": "dashboard",
        "label": "Dashboard",
        "label_plural": "Dashboards",
        "icon": "LayoutDashboard",
        "description": "Analytics and reporting dashboard",
        "sort_order": 8,
        "number_prefix": "",
        "number_format": "",
        "number_reset_period": "never",
    },
    {
        "name": "users",
        "label": "User",
        "label_plural": "Users",
        "icon": "UserCog",
        "description": "User accounts and settings",
        "sort_order": 9,
        "number_prefix": "",
        "number_format": "",
        "number_reset_period": "never",
    },
    {
        "name": "audit",
        "label": "Audit Log",
        "label_plural": "Audit Logs",
        "icon": "Shield",
        "description": "System audit trail",
        "sort_order": 10,
        "number_prefix": "",
        "number_format": "",
        "number_reset_period": "never",
    },
    {
        "name": "emails",
        "label": "Email",
        "label_plural": "Emails",
        "icon": "Mail",
        "description": "Email accounts and messaging",
        "sort_order": 11,
        "number_prefix": "",
        "number_format": "",
        "number_reset_period": "never",
    },
    {
        "name": "notifications",
        "label": "Notification",
        "label_plural": "Notifications",
        "icon": "Bell",
        "description": "System notifications and alerts",
        "sort_order": 12,
        "number_prefix": "",
        "number_format": "",
        "number_reset_period": "never",
    },
    {
        "name": "workflows",
        "label": "Workflow",
        "label_plural": "Workflows",
        "icon": "Workflow",
        "description": "Business process automation",
        "sort_order": 13,
        "number_prefix": "",
        "number_format": "",
        "number_reset_period": "never",
    },
    {
        "name": "portal",
        "label": "Portal",
        "label_plural": "Portals",
        "icon": "Globe",
        "description": "Client portal access",
        "sort_order": 14,
        "number_prefix": "",
        "number_format": "",
        "number_reset_period": "never",
    },
    {
        "name": "internal_tickets",
        "label": "Internal Ticket",
        "label_plural": "Internal Tickets",
        "icon": "Ticket",
        "description": "Internal support tickets",
        "sort_order": 15,
        "number_prefix": "IT",
        "number_format": "{prefix}-{year}-{seq:04d}",
        "number_reset_period": "yearly",
    },
    {
        "name": "sales_insights",
        "label": "Sales Insight",
        "label_plural": "Sales Insights",
        "icon": "TrendingUp",
        "description": "Sales analytics and insights",
        "sort_order": 16,
        "number_prefix": "",
        "number_format": "",
        "number_reset_period": "never",
    },
    {
        "name": "forecasts",
        "label": "Forecast",
        "label_plural": "Forecasts",
        "icon": "BarChart3",
        "description": "Revenue forecasting and quotas",
        "sort_order": 17,
        "number_prefix": "",
        "number_format": "",
        "number_reset_period": "never",
    },
    {
        "name": "reports",
        "label": "Report",
        "label_plural": "Reports",
        "icon": "FileBarChart",
        "description": "Custom reports and analytics",
        "sort_order": 18,
        "number_prefix": "",
        "number_format": "",
        "number_reset_period": "never",
    },
    {
        "name": "esign",
        "label": "Esign Document",
        "label_plural": "Esign Documents",
        "icon": "FileSignature",
        "description": "Electronic signature documents",
        "sort_order": 19,
        "number_prefix": "ES",
        "number_format": "{prefix}-{year}-{seq:04d}",
        "number_reset_period": "yearly",
    },
    {
        "name": "approvals",
        "label": "Approval",
        "label_plural": "Approvals",
        "icon": "Stamp",
        "description": "Approval automation processes",
        "sort_order": 20,
        "number_prefix": "",
        "number_format": "",
        "number_reset_period": "never",
    },
    {
        "name": "products",
        "label": "Product",
        "label_plural": "Products",
        "icon": "Package",
        "description": "Product catalog",
        "sort_order": 21,
        "number_prefix": "PR",
        "number_format": "{prefix}-{year}-{seq:04d}",
        "number_reset_period": "yearly",
    },
    {
        "name": "services_catalog",
        "label": "Service",
        "label_plural": "Services",
        "icon": "Wrench",
        "description": "Service catalog",
        "sort_order": 22,
        "number_prefix": "SV",
        "number_format": "{prefix}-{year}-{seq:04d}",
        "number_reset_period": "yearly",
    },
    {
        "name": "vendors",
        "label": "Vendor",
        "label_plural": "Vendors",
        "icon": "Users2",
        "description": "Vendors and suppliers",
        "sort_order": 23,
        "number_prefix": "",
        "number_format": "",
        "number_reset_period": "never",
    },
    {
        "name": "invoices",
        "label": "Invoice",
        "label_plural": "Invoices",
        "icon": "FileText",
        "description": "Customer invoices",
        "sort_order": 24,
        "number_prefix": "INV",
        "number_format": "{prefix}-{year}-{seq:04d}",
        "number_reset_period": "yearly",
    },
    {
        "name": "sales_orders",
        "label": "Sales Order",
        "label_plural": "Sales Orders",
        "icon": "ShoppingCart",
        "description": "Sales orders",
        "sort_order": 25,
        "number_prefix": "SO",
        "number_format": "{prefix}-{year}-{seq:04d}",
        "number_reset_period": "yearly",
    },
    {
        "name": "purchase_orders",
        "label": "Purchase Order",
        "label_plural": "Purchase Orders",
        "icon": "ClipboardList",
        "description": "Purchase orders",
        "sort_order": 26,
        "number_prefix": "PO",
        "number_format": "{prefix}-{year}-{seq:04d}",
        "number_reset_period": "yearly",
    },
    {
        "name": "payments",
        "label": "Payment",
        "label_plural": "Payments",
        "icon": "CreditCard",
        "description": "Payment records",
        "sort_order": 27,
        "number_prefix": "PAY",
        "number_format": "{prefix}-{year}-{seq:04d}",
        "number_reset_period": "yearly",
    },
    {
        "name": "work_orders",
        "label": "Work Order",
        "label_plural": "Work Orders",
        "icon": "Hammer",
        "description": "Work orders",
        "sort_order": 28,
        "number_prefix": "WO",
        "number_format": "{prefix}-{year}-{seq:04d}",
        "number_reset_period": "yearly",
    },
    {
        "name": "assets",
        "label": "Asset",
        "label_plural": "Assets",
        "icon": "Landmark",
        "description": "Customer assets",
        "sort_order": 29,
        "number_prefix": "",
        "number_format": "",
        "number_reset_period": "never",
    },
    {
        "name": "price_books",
        "label": "Price Book",
        "label_plural": "Price Books",
        "icon": "BookOpen",
        "description": "Price lists",
        "sort_order": 30,
        "number_prefix": "",
        "number_format": "",
        "number_reset_period": "never",
    },
]


PICKLIST_SEED = [
    {
        "name": "case_status",
        "label": "Case Status",
        "module_name": "cases",
        "values": [
            {"value": "new", "label": "New", "sort_order": 0, "color": "#6b7280"},
            {
                "value": "waiting_for_documents",
                "label": "Waiting for Documents",
                "sort_order": 1,
                "color": "#f59e0b",
            },
            {
                "value": "in_progress",
                "label": "In Progress",
                "sort_order": 2,
                "color": "#3b82f6",
            },
            {
                "value": "under_review",
                "label": "Under Review",
                "sort_order": 3,
                "color": "#8b5cf6",
            },
            {
                "value": "ready_to_file",
                "label": "Ready to File",
                "sort_order": 4,
                "color": "#06b6d4",
            },
            {"value": "filed", "label": "Filed", "sort_order": 5, "color": "#10b981"},
            {
                "value": "completed",
                "label": "Completed",
                "sort_order": 6,
                "color": "#22c55e",
            },
            {"value": "closed", "label": "Closed", "sort_order": 7, "color": "#9ca3af"},
        ],
    },
    {
        "name": "case_type",
        "label": "Case Type",
        "module_name": "cases",
        "values": [
            {"value": "individual_1040", "label": "Individual (1040)", "sort_order": 0},
            {"value": "corporate_1120", "label": "Corporate (1120)", "sort_order": 1},
            {"value": "s_corp_1120s", "label": "S-Corp (1120-S)", "sort_order": 2},
            {
                "value": "partnership_1065",
                "label": "Partnership (1065)",
                "sort_order": 3,
            },
            {"value": "nonprofit_990", "label": "Nonprofit (990)", "sort_order": 4},
            {"value": "trust_1041", "label": "Trust (1041)", "sort_order": 5},
            {"value": "payroll", "label": "Payroll", "sort_order": 6},
            {"value": "sales_tax", "label": "Sales Tax", "sort_order": 7},
            {"value": "amendment", "label": "Amendment", "sort_order": 8},
            {"value": "other", "label": "Other", "sort_order": 9},
        ],
    },
    {
        "name": "quote_stage",
        "label": "Quote Stage",
        "module_name": "quotes",
        "values": [
            {
                "value": "draft",
                "label": "Draft",
                "sort_order": 0,
                "color": "#6b7280",
                "is_default": True,
            },
            {"value": "sent", "label": "Sent", "sort_order": 1, "color": "#3b82f6"},
            {
                "value": "accepted",
                "label": "Accepted",
                "sort_order": 2,
                "color": "#22c55e",
            },
            {
                "value": "rejected",
                "label": "Rejected",
                "sort_order": 3,
                "color": "#ef4444",
            },
            {
                "value": "expired",
                "label": "Expired",
                "sort_order": 4,
                "color": "#9ca3af",
            },
        ],
    },
    {
        "name": "contact_status",
        "label": "Contact Status",
        "module_name": "contacts",
        "values": [
            {
                "value": "active",
                "label": "Active",
                "sort_order": 0,
                "color": "#22c55e",
                "is_default": True,
            },
            {
                "value": "inactive",
                "label": "Inactive",
                "sort_order": 1,
                "color": "#9ca3af",
            },
            {"value": "lead", "label": "Lead", "sort_order": 2, "color": "#f59e0b"},
        ],
    },
    {
        "name": "service_type",
        "label": "Service Type",
        "module_name": "quotes",
        "values": [
            {"value": "individual_1040", "label": "Individual (1040)", "sort_order": 0},
            {"value": "corporate_1120", "label": "Corporate (1120)", "sort_order": 1},
            {"value": "s_corp_1120s", "label": "S-Corp (1120-S)", "sort_order": 2},
            {
                "value": "partnership_1065",
                "label": "Partnership (1065)",
                "sort_order": 3,
            },
            {"value": "nonprofit_990", "label": "Nonprofit (990)", "sort_order": 4},
            {"value": "trust_1041", "label": "Trust (1041)", "sort_order": 5},
            {"value": "payroll", "label": "Payroll", "sort_order": 6},
            {"value": "sales_tax", "label": "Sales Tax", "sort_order": 7},
            {"value": "bookkeeping", "label": "Bookkeeping", "sort_order": 8},
            {"value": "consulting", "label": "Consulting", "sort_order": 9},
            {"value": "amendment", "label": "Amendment", "sort_order": 10},
            {"value": "other", "label": "Other", "sort_order": 11},
        ],
    },
]


class Command(BaseCommand):
    help = "Seed CRM modules and system picklists"

    def handle(self, *args, **options):
        self._seed_modules()
        self._seed_picklists()
        self.stdout.write(self.style.SUCCESS("Module seed data loaded successfully."))

    def _seed_modules(self):
        for data in MODULE_SEED:
            module, created = CRMModule.objects.update_or_create(
                name=data["name"],
                defaults={
                    "label": data["label"],
                    "label_plural": data["label_plural"],
                    "icon": data["icon"],
                    "description": data["description"],
                    "sort_order": data["sort_order"],
                    "number_prefix": data["number_prefix"],
                    "number_format": data["number_format"],
                    "number_reset_period": data["number_reset_period"],
                },
            )
            action = "Created" if created else "Updated"
            self.stdout.write(f"  {action} module: {module.name}")

    def _seed_picklists(self):
        for data in PICKLIST_SEED:
            module = None
            if data.get("module_name"):
                try:
                    module = CRMModule.objects.get(name=data["module_name"])
                except CRMModule.DoesNotExist:
                    self.stdout.write(
                        self.style.WARNING(
                            f"  Module '{data['module_name']}' not found, "
                            f"skipping picklist '{data['name']}'"
                        )
                    )
                    continue

            picklist, created = Picklist.objects.update_or_create(
                name=data["name"],
                module=module,
                defaults={
                    "label": data["label"],
                    "is_system": True,
                },
            )
            action = "Created" if created else "Updated"
            self.stdout.write(f"  {action} picklist: {picklist.name}")

            for val_data in data.get("values", []):
                PicklistValue.objects.update_or_create(
                    picklist=picklist,
                    value=val_data["value"],
                    defaults={
                        "label": val_data["label"],
                        "sort_order": val_data.get("sort_order", 0),
                        "is_default": val_data.get("is_default", False),
                        "color": val_data.get("color", ""),
                    },
                )
