# Generated by Django 5.1.15 on 2026-02-03 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('case_type', models.CharField(db_index=True, max_length=30)),
                ('tax_year', models.PositiveIntegerField(blank=True, db_index=True, help_text='Leave blank for a default template that applies to all years.', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['case_type', '-tax_year'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('doc_type', models.CharField(blank=True, default='', help_text='If set, auto-checks when a document of this type is uploaded.', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TaxCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='case number')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('case_type', models.CharField(choices=[('individual_1040', 'Individual (1040)'), ('corporate_1120', 'Corporate (1120)'), ('s_corp_1120s', 'S-Corp (1120-S)'), ('partnership_1065', 'Partnership (1065)'), ('nonprofit_990', 'Nonprofit (990)'), ('trust_1041', 'Trust (1041)'), ('payroll', 'Payroll'), ('sales_tax', 'Sales Tax'), ('amendment', 'Amendment'), ('other', 'Other')], db_index=True, max_length=30, verbose_name='case type')),
                ('fiscal_year', models.PositiveIntegerField(db_index=True, verbose_name='fiscal year')),
                ('status', models.CharField(choices=[('new', 'New'), ('waiting_for_documents', 'Waiting for Documents'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('ready_to_file', 'Ready to File'), ('filed', 'Filed'), ('completed', 'Completed'), ('closed', 'Closed')], db_index=True, default='new', max_length=25, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='priority')),
                ('estimated_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='estimated fee')),
                ('actual_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='actual fee')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('extension_date', models.DateField(blank=True, null=True, verbose_name='extension date')),
                ('filed_date', models.DateField(blank=True, null=True, verbose_name='filed date')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='completed date')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='closed date')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
            ],
            options={
                'verbose_name': 'tax case',
                'verbose_name_plural': 'tax cases',
                'db_table': 'crm_tax_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxCaseNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='content')),
                ('is_internal', models.BooleanField(default=True, help_text='Internal notes are only visible to staff.', verbose_name='internal note')),
            ],
            options={
                'verbose_name': 'tax case note',
                'verbose_name_plural': 'tax case notes',
                'db_table': 'crm_tax_case_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('doc_type', models.CharField(blank=True, default='', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cases.casechecklist')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
