# Generated by Django 5.1.15 on 2026-02-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcase',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='custom fields'),
        ),
    ]
