# Generated by Django 5.1.15 on 2026-02-14 18:40

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_hours", "0001_initial"),
        ("cases", "0003_taxcase_custom_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SLA",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "response_time_urgent",
                    models.IntegerField(
                        default=1,
                        help_text="Hours to first response for urgent priority",
                    ),
                ),
                (
                    "response_time_high",
                    models.IntegerField(
                        default=4, help_text="Hours to first response for high priority"
                    ),
                ),
                (
                    "response_time_medium",
                    models.IntegerField(
                        default=8,
                        help_text="Hours to first response for medium priority",
                    ),
                ),
                (
                    "response_time_low",
                    models.IntegerField(
                        default=24, help_text="Hours to first response for low priority"
                    ),
                ),
                (
                    "resolution_time_urgent",
                    models.IntegerField(
                        default=4, help_text="Hours to resolution for urgent priority"
                    ),
                ),
                (
                    "resolution_time_high",
                    models.IntegerField(
                        default=24, help_text="Hours to resolution for high priority"
                    ),
                ),
                (
                    "resolution_time_medium",
                    models.IntegerField(
                        default=48, help_text="Hours to resolution for medium priority"
                    ),
                ),
                (
                    "resolution_time_low",
                    models.IntegerField(
                        default=72, help_text="Hours to resolution for low priority"
                    ),
                ),
                (
                    "use_business_hours",
                    models.BooleanField(
                        default=True,
                        help_text="Calculate SLA based on business hours only",
                    ),
                ),
                ("escalation_enabled", models.BooleanField(default=True)),
                ("escalation_notify_assignee", models.BooleanField(default=True)),
                ("escalation_notify_manager", models.BooleanField(default=True)),
                (
                    "escalation_email",
                    models.EmailField(
                        blank=True,
                        help_text="Additional email for escalation notifications",
                        max_length=254,
                    ),
                ),
                (
                    "applicable_case_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of case types this SLA applies to (empty = all)",
                    ),
                ),
                (
                    "business_hours",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slas",
                        to="business_hours.businesshours",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_slas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA",
                "verbose_name_plural": "SLAs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EscalationRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage of time elapsed"),
                            ("hours_before", "Hours before breach"),
                            ("on_breach", "On breach"),
                            ("hours_after", "Hours after breach"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "trigger_value",
                    models.IntegerField(
                        default=0,
                        help_text="Percentage (0-100) or hours depending on trigger type",
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("response", "Response SLA"),
                            ("resolution", "Resolution SLA"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("notify_assignee", models.BooleanField(default=True)),
                ("notify_manager", models.BooleanField(default=False)),
                (
                    "notify_emails",
                    models.TextField(
                        blank=True, help_text="Comma-separated email addresses"
                    ),
                ),
                (
                    "change_priority",
                    models.CharField(
                        blank=True,
                        choices=[("urgent", "Urgent"), ("high", "High")],
                        help_text="Optionally increase priority on escalation",
                        max_length=20,
                    ),
                ),
                (
                    "email_subject",
                    models.CharField(
                        default="SLA Alert: Case {{case.case_number}} requires attention",
                        max_length=200,
                    ),
                ),
                (
                    "email_body",
                    models.TextField(
                        default="Case {{case.case_number}} is {{status}} for {{sla_type}} SLA.\n\nCase: {{case.title}}\nPriority: {{case.priority}}\nAssigned to: {{case.assigned_to}}\n\nPlease take action immediately."
                    ),
                ),
                (
                    "notify_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="escalation_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reassign_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalation_reassignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalation_rules",
                        to="cases.sla",
                    ),
                ),
            ],
            options={
                "ordering": ["sla", "order"],
            },
        ),
        migrations.CreateModel(
            name="CaseSLAStatus",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "response_status",
                    models.CharField(
                        choices=[
                            ("on_track", "On Track"),
                            ("at_risk", "At Risk"),
                            ("breached", "Breached"),
                            ("paused", "Paused"),
                            ("met", "Met"),
                            ("na", "Not Applicable"),
                        ],
                        default="on_track",
                        max_length=20,
                    ),
                ),
                ("response_target", models.DateTimeField(blank=True, null=True)),
                ("response_met_at", models.DateTimeField(blank=True, null=True)),
                ("response_breached", models.BooleanField(default=False)),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("on_track", "On Track"),
                            ("at_risk", "At Risk"),
                            ("breached", "Breached"),
                            ("paused", "Paused"),
                            ("met", "Met"),
                            ("na", "Not Applicable"),
                        ],
                        default="on_track",
                        max_length=20,
                    ),
                ),
                ("resolution_target", models.DateTimeField(blank=True, null=True)),
                ("resolution_met_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_breached", models.BooleanField(default=False)),
                ("is_paused", models.BooleanField(default=False)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_paused_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("pause_reason", models.CharField(blank=True, max_length=200)),
                ("time_to_response", models.DurationField(blank=True, null=True)),
                ("time_to_resolution", models.DurationField(blank=True, null=True)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_status",
                        to="cases.taxcase",
                    ),
                ),
                (
                    "sla",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_statuses",
                        to="cases.sla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case SLA Status",
                "verbose_name_plural": "Case SLA Statuses",
            },
        ),
        migrations.CreateModel(
            name="SLABreach",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "breach_type",
                    models.CharField(
                        choices=[
                            ("response", "Response Time Breach"),
                            ("resolution", "Resolution Time Breach"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_time",
                    models.DateTimeField(help_text="When the SLA target was"),
                ),
                (
                    "breach_time",
                    models.DateTimeField(help_text="When the breach occurred"),
                ),
                (
                    "breach_duration",
                    models.DurationField(
                        help_text="How long the breach lasted/is lasting"
                    ),
                ),
                ("case_priority", models.CharField(max_length=20)),
                ("case_status", models.CharField(max_length=50)),
                ("escalation_sent", models.BooleanField(default=False)),
                ("escalation_sent_at", models.DateTimeField(blank=True, null=True)),
                ("escalation_acknowledged", models.BooleanField(default=False)),
                (
                    "escalation_acknowledged_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sla_breaches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_breaches",
                        to="cases.taxcase",
                    ),
                ),
                (
                    "escalation_acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_breaches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sla",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="breaches",
                        to="cases.sla",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Breach",
                "verbose_name_plural": "SLA Breaches",
                "ordering": ["-breach_time"],
            },
        ),
    ]
