# Generated by Django 5.1.15 on 2026-02-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_sla_escalationrule_caseslastatus_slabreach"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxcase",
            name="case_number",
            field=models.CharField(
                db_index=True, max_length=30, unique=True, verbose_name="case number"
            ),
        ),
    ]
