# Generated by Django 5.1.15 on 2026-02-03 20:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("contacts", "0001_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientPortalAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(max_length=255, verbose_name="password hash"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "reset_token",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="reset token",
                    ),
                ),
                (
                    "reset_token_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reset token expires"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_access",
                        to="contacts.contact",
                        verbose_name="contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "client portal access",
                "verbose_name_plural": "client portal accesses",
                "db_table": "crm_client_portal_access",
            },
        ),
        migrations.CreateModel(
            name="PortalDocumentUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reviewed at"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="rejection reason"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_uploads",
                        to="cases.taxcase",
                        verbose_name="case",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_uploads",
                        to="contacts.contact",
                        verbose_name="contact",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_upload",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "portal document upload",
                "verbose_name_plural": "portal document uploads",
                "db_table": "crm_portal_document_uploads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortalMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("client_to_staff", "Client to Staff"),
                            ("staff_to_client", "Staff to Client"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="subject")),
                ("body", models.TextField(verbose_name="body")),
                ("is_read", models.BooleanField(default=False, verbose_name="read")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_messages",
                        to="cases.taxcase",
                        verbose_name="case",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_messages",
                        to="contacts.contact",
                        verbose_name="contact",
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="portal.portalmessage",
                        verbose_name="parent message",
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_messages_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sender (staff)",
                    ),
                ),
            ],
            options={
                "verbose_name": "portal message",
                "verbose_name_plural": "portal messages",
                "db_table": "crm_portal_messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
