# Generated by Django 5.1.15 on 2026-02-05 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portal_url', models.URLField(blank=True, default='', help_text='The public URL of the customer portal.', max_length=500, verbose_name='portal URL')),
                ('support_notification_days', models.PositiveIntegerField(default=7, help_text='Days before expiration to notify support.', verbose_name='contact support notification (days before)')),
                ('login_details_template', models.CharField(blank=True, default='Customer Portal Login Link', max_length=255, verbose_name='login details template')),
                ('forgot_password_template', models.CharField(blank=True, default='Customer Portal Forgot Password Reset Link', max_length=255, verbose_name='forgot password template')),
                ('custom_css_url', models.URLField(blank=True, default='', max_length=500, verbose_name='CSS URL for custom theme')),
                ('default_scope', models.CharField(choices=[('all', 'All'), ('own', 'Own Records Only')], default='all', max_length=20, verbose_name='default scope')),
                ('session_timeout_hours', models.CharField(choices=[('1', '1 hour(s)'), ('2', '2 hour(s)'), ('4', '4 hour(s)'), ('8', '8 hour(s)'), ('12', '12 hour(s)'), ('24', '24 hour(s)')], default='4', max_length=5, verbose_name='inactive portal session logout interval')),
                ('announcement_html', models.TextField(blank=True, default='', verbose_name='announcement')),
                ('greeting_type', models.CharField(choices=[('standard', 'Standard greeting'), ('time_based', 'Time based greeting')], default='standard', max_length=20, verbose_name='greeting type')),
                ('account_rep_widget_enabled', models.BooleanField(default=False, verbose_name='account representatives widget enabled')),
                ('recent_documents_widget_enabled', models.BooleanField(default=True, verbose_name='recent documents record widget enabled')),
                ('recent_faq_widget_enabled', models.BooleanField(default=True, verbose_name='recent FAQ record widget enabled')),
                ('recent_cases_widget_enabled', models.BooleanField(default=True, verbose_name='recent cases record widget enabled')),
                ('chart_open_cases_priority', models.BooleanField(default=True, verbose_name='chart: open cases by priority')),
                ('chart_cases_resolution_time', models.BooleanField(default=True, verbose_name='chart: cases resolution time by priority')),
                ('chart_projects_by_status', models.BooleanField(default=False, verbose_name='chart: projects by status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_default_assignee', to=settings.AUTH_USER_MODEL, verbose_name='default assignee')),
            ],
            options={
                'verbose_name': 'portal configuration',
                'verbose_name_plural': 'portal configurations',
                'db_table': 'crm_portal_configuration',
            },
        ),
        migrations.CreateModel(
            name='PortalShortcut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shortcut_type', models.CharField(choices=[('add_document', 'Add Document'), ('create_case', 'Create Case'), ('open_cases', 'Open Cases'), ('custom', 'Custom Link')], max_length=50, verbose_name='shortcut type')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('custom_url', models.CharField(blank=True, default='', max_length=500, verbose_name='custom URL')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcuts', to='portal.portalconfiguration', verbose_name='configuration')),
            ],
            options={
                'verbose_name': 'portal shortcut',
                'verbose_name_plural': 'portal shortcuts',
                'db_table': 'crm_portal_shortcuts',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PortalMenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_name', models.CharField(help_text="Internal module identifier, e.g., 'cases', 'invoices'.", max_length=100, verbose_name='module name')),
                ('label', models.CharField(help_text='Display label in the portal menu.', max_length=100, verbose_name='label')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='portal.portalconfiguration', verbose_name='configuration')),
            ],
            options={
                'verbose_name': 'portal menu item',
                'verbose_name_plural': 'portal menu items',
                'db_table': 'crm_portal_menu_items',
                'ordering': ['sort_order'],
                'unique_together': {('configuration', 'module_name')},
            },
        ),
        migrations.CreateModel(
            name='PortalModuleFieldConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_name', models.CharField(help_text="Module: 'contacts' or 'organizations'.", max_length=100, verbose_name='module name')),
                ('field_name', models.CharField(max_length=100, verbose_name='field name')),
                ('field_label', models.CharField(max_length=100, verbose_name='field label')),
                ('permission', models.CharField(choices=[('hidden', 'Hidden'), ('read_only', 'Read Only'), ('read_write', 'Read and Write')], default='read_only', max_length=20, verbose_name='permission')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='mandatory')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_configs', to='portal.portalconfiguration', verbose_name='configuration')),
            ],
            options={
                'verbose_name': 'portal module field config',
                'verbose_name_plural': 'portal module field configs',
                'db_table': 'crm_portal_module_field_configs',
                'ordering': ['module_name', 'sort_order'],
                'unique_together': {('configuration', 'module_name', 'field_name')},
            },
        ),
    ]
