# Generated by Django 5.1.15 on 2026-02-06 20:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0007_contacttag_contacttagassignment"),
        ("portal", "0002_portalconfiguration_portalshortcut_portalmenuitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalDeviceToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Expo push notification token",
                        max_length=500,
                        unique=True,
                        verbose_name="push token",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")],
                        max_length=20,
                        verbose_name="platform",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this device should receive notifications",
                        verbose_name="active",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last used"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to="contacts.contact",
                        verbose_name="contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "portal device token",
                "verbose_name_plural": "portal device tokens",
                "db_table": "crm_portal_device_tokens",
                "indexes": [
                    models.Index(
                        fields=["contact", "is_active"],
                        name="crm_portal__contact_ebf37a_idx",
                    )
                ],
            },
        ),
    ]
