# Generated by Django 5.1

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("cases", "0001_initial"),
        ("contacts", "0001_initial"),
        ("portal", "0003_portaldevicetoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_message", "New Message"),
                            ("case_update", "Case Update"),
                            ("document_status", "Document Status"),
                            ("appointment_reminder", "Appointment Reminder"),
                            ("system", "System"),
                        ],
                        max_length=30,
                        verbose_name="type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="message"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="read"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_notifications",
                        to="contacts.contact",
                        verbose_name="contact",
                    ),
                ),
                (
                    "related_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_notifications",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "related_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_notifications",
                        to="cases.taxcase",
                    ),
                ),
                (
                    "related_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="portal.portalmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "portal notification",
                "verbose_name_plural": "portal notifications",
                "db_table": "crm_portal_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="portalnotification",
            index=models.Index(
                fields=["contact", "is_read", "-created_at"],
                name="crm_portal__contact_f3d8b4_idx",
            ),
        ),
    ]
