# Generated by Django 5.1.15 on 2026-02-21 19:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0005_increase_phone_field_length'),
        ('portal', '0005_rename_crm_portal__contact_f3d8b4_idx_crm_portal__contact_e9dcdf_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPortalAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_manage_products', models.BooleanField(default=True, help_text='Create, edit, delete products in inventory.', verbose_name='can manage products')),
                ('can_manage_services', models.BooleanField(default=True, help_text='Create, edit, delete services in inventory.', verbose_name='can manage services')),
                ('can_create_invoices', models.BooleanField(default=True, help_text='Create and manage invoices.', verbose_name='can create invoices')),
                ('can_create_quotes', models.BooleanField(default=True, help_text='Create and manage quotes/estimates.', verbose_name='can create quotes')),
                ('can_view_reports', models.BooleanField(default=True, help_text='View billing dashboard and reports.', verbose_name='can view reports')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portal_access', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_access', to='portal.clientportalaccess', verbose_name='portal access')),
                ('tenant', models.ForeignKey(help_text='The corporation this billing access is scoped to.', on_delete=django.db.models.deletion.CASCADE, related_name='billing_portal_accesses', to='corporations.corporation', verbose_name='tenant corporation')),
            ],
            options={
                'verbose_name': 'billing portal access',
                'verbose_name_plural': 'billing portal accesses',
                'db_table': 'crm_billing_portal_access',
            },
        ),
    ]
