# Generated by Django 5.1.15 on 2026-02-14 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0004_sla_escalationrule_caseslastatus_slabreach"),
        ("contacts", "0007_contacttag_contacttagassignment"),
        ("corporations", "0003_add_vtiger_organization_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CallQueue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("ring_all", "Ring All"),
                            ("round_robin", "Round Robin"),
                            ("least_recent", "Least Recent"),
                            ("random", "Random"),
                            ("linear", "Linear"),
                        ],
                        default="round_robin",
                        max_length=20,
                    ),
                ),
                ("timeout", models.IntegerField(default=30)),
                ("max_wait_time", models.IntegerField(default=300)),
                ("hold_music_url", models.URLField(blank=True)),
                ("announce_position", models.BooleanField(default=True)),
                ("announce_wait_time", models.BooleanField(default=False)),
                (
                    "overflow_action",
                    models.CharField(default="voicemail", max_length=50),
                ),
                ("overflow_destination", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Call Queue",
                "verbose_name_plural": "Call Queues",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CallSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_record_all", models.BooleanField(default=False)),
                ("record_inbound", models.BooleanField(default=True)),
                ("record_outbound", models.BooleanField(default=True)),
                ("recording_format", models.CharField(default="mp3", max_length=10)),
                ("recording_retention_days", models.IntegerField(default=365)),
                ("transcription_enabled", models.BooleanField(default=False)),
                (
                    "transcription_language",
                    models.CharField(default="en-US", max_length=10),
                ),
                ("default_ring_timeout", models.IntegerField(default=30)),
                ("missed_call_notification", models.BooleanField(default=True)),
                ("voicemail_notification", models.BooleanField(default=True)),
                ("click_to_call_enabled", models.BooleanField(default=True)),
                ("confirm_before_dial", models.BooleanField(default=True)),
                ("enforce_business_hours", models.BooleanField(default=False)),
                (
                    "after_hours_action",
                    models.CharField(default="voicemail", max_length=50),
                ),
                ("after_hours_message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Call Settings",
                "verbose_name_plural": "Call Settings",
            },
        ),
        migrations.CreateModel(
            name="TelephonyProvider",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("twilio", "Twilio"),
                            ("ringcentral", "RingCentral"),
                            ("vonage", "Vonage"),
                            ("asterisk", "Asterisk/FreePBX"),
                            ("custom", "Custom SIP"),
                        ],
                        default="twilio",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("account_sid", models.CharField(blank=True, max_length=255)),
                ("auth_token", models.CharField(blank=True, max_length=255)),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("api_secret", models.CharField(blank=True, max_length=255)),
                ("webhook_url", models.URLField(blank=True)),
                ("default_caller_id", models.CharField(blank=True, max_length=20)),
                ("recording_enabled", models.BooleanField(default=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Telephony Provider",
                "verbose_name_plural": "Telephony Providers",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="CallQueueMember",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_available", models.BooleanField(default=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("pause_reason", models.CharField(blank=True, max_length=100)),
                ("calls_taken", models.IntegerField(default=0)),
                ("last_call_at", models.DateTimeField(blank=True, null=True)),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calls.callqueue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Member",
                "verbose_name_plural": "Queue Members",
                "ordering": ["priority", "-calls_taken"],
                "unique_together": {("queue", "user")},
            },
        ),
        migrations.AddField(
            model_name="callqueue",
            name="members",
            field=models.ManyToManyField(
                related_name="call_queues",
                through="calls.CallQueueMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CallScript",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "script_type",
                    models.CharField(
                        choices=[
                            ("cold_call", "Cold Call"),
                            ("follow_up", "Follow-up"),
                            ("support", "Support"),
                            ("sales", "Sales"),
                            ("survey", "Survey"),
                        ],
                        default="sales",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("content", models.TextField()),
                ("sections", models.JSONField(default=list)),
                ("times_used", models.IntegerField(default=0)),
                ("avg_success_rate", models.FloatField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_call_scripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Script",
                "verbose_name_plural": "Call Scripts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PhoneLine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("friendly_name", models.CharField(blank=True, max_length=100)),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound Only"),
                            ("outbound", "Outbound Only"),
                            ("both", "Inbound & Outbound"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_department", models.CharField(blank=True, max_length=100)),
                ("voicemail_enabled", models.BooleanField(default=True)),
                ("voicemail_greeting_url", models.URLField(blank=True)),
                ("forward_to", models.CharField(blank=True, max_length=20)),
                ("ring_timeout", models.IntegerField(default=30)),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_lines",
                        to="calls.telephonyprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phone Line",
                "verbose_name_plural": "Phone Lines",
                "ordering": ["phone_number"],
            },
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("ringing", "Ringing"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("busy", "Busy"),
                            ("no_answer", "No Answer"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                            ("voicemail", "Voicemail"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Call"),
                            ("follow_up", "Follow-up"),
                            ("cold_call", "Cold Call"),
                            ("support", "Support Call"),
                            ("sales", "Sales Call"),
                            ("callback", "Callback Request"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("from_number", models.CharField(max_length=20)),
                ("to_number", models.CharField(max_length=20)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration", models.IntegerField(default=0)),
                ("ring_duration", models.IntegerField(default=0)),
                ("is_recorded", models.BooleanField(default=False)),
                ("recording_url", models.URLField(blank=True)),
                ("recording_duration", models.IntegerField(default=0)),
                ("transcription", models.TextField(blank=True)),
                ("transcription_status", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("outcome", models.CharField(blank=True, max_length=100)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("call_quality_score", models.IntegerField(blank=True, null=True)),
                ("customer_sentiment", models.CharField(blank=True, max_length=20)),
                ("provider_data", models.JSONField(blank=True, default=dict)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="cases.taxcase",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="contacts.contact",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="corporations.corporation",
                    ),
                ),
                (
                    "transferred_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferred_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phone_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="calls.phoneline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call",
                "verbose_name_plural": "Calls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Voicemail",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("caller_number", models.CharField(max_length=20)),
                ("caller_name", models.CharField(blank=True, max_length=100)),
                ("audio_url", models.URLField()),
                ("duration", models.IntegerField(default=0)),
                ("transcription", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("listened", "Listened"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("listened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voicemails",
                        to="calls.call",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voicemails",
                        to="contacts.contact",
                    ),
                ),
                (
                    "listened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listened_voicemails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phone_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voicemails",
                        to="calls.phoneline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voicemail",
                "verbose_name_plural": "Voicemails",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["direction", "status"], name="calls_call_directi_bfe6a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["from_number"], name="calls_call_from_nu_4c17b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["to_number"], name="calls_call_to_numb_7a42d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["started_at"], name="calls_call_started_a8efe0_idx"
            ),
        ),
    ]
