# Generated by Django 5.1.15 on 2026-02-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="from_number",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="call",
            name="to_number",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="phoneline",
            name="forward_to",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="phoneline",
            name="phone_number",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="telephonyprovider",
            name="default_caller_id",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
