# Generated by Django 5.1.15 on 2026-02-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0002_fix_field_lengths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voicemail",
            name="caller_number",
            field=models.CharField(max_length=30),
        ),
    ]
