# Generated by Django 5.1.15 on 2026-02-05 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('timezone', models.CharField(default='America/New_York', max_length=100, verbose_name='operational time zone')),
                ('is_default', models.BooleanField(default=False, help_text='If checked, this will be the default business hours.', verbose_name='default business hours')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'business hours',
                'verbose_name_plural': 'business hours',
                'db_table': 'crm_business_hours',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day of week')),
                ('is_working', models.BooleanField(default=True, verbose_name='is working day')),
                ('business_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='business_hours.businesshours', verbose_name='business hours')),
            ],
            options={
                'verbose_name': 'working day',
                'verbose_name_plural': 'working days',
                'db_table': 'crm_business_hours_working_days',
                'ordering': ['day_of_week'],
                'unique_together': {('business_hours', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='WorkingInterval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort order')),
                ('working_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='business_hours.workingday', verbose_name='working day')),
            ],
            options={
                'verbose_name': 'working interval',
                'verbose_name_plural': 'working intervals',
                'db_table': 'crm_business_hours_working_intervals',
                'ordering': ['sort_order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='date')),
                ('name', models.CharField(max_length=255, verbose_name='holiday name')),
                ('business_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='business_hours.businesshours', verbose_name='business hours')),
            ],
            options={
                'verbose_name': 'holiday',
                'verbose_name_plural': 'holidays',
                'db_table': 'crm_business_hours_holidays',
                'ordering': ['date'],
                'unique_together': {('business_hours', 'date')},
            },
        ),
    ]
