# Generated by Django 5.1.15 on 2026-02-04 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_alter_modulepermission_module_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ticket_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="ticket number",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("wait_for_response", "Wait For Response"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("web", "Web"),
                            ("chat", "Chat"),
                            ("portal", "Portal"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="channel",
                    ),
                ),
                (
                    "resolution",
                    models.TextField(blank=True, default="", verbose_name="resolution"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="email"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("general", "General"),
                            ("technical", "Technical"),
                            ("billing", "Billing"),
                            ("hr", "HR"),
                            ("it", "IT"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "deferred_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="deferred date"
                    ),
                ),
                (
                    "resolution_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed", "Fixed"),
                            ("wont_fix", "Won't Fix"),
                            ("duplicate", "Duplicate"),
                            ("deferred", "Deferred"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="resolution type",
                    ),
                ),
                (
                    "sla_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="SLA name"
                    ),
                ),
                (
                    "sla_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Expected resolution time in hours.",
                        null=True,
                        verbose_name="SLA hours",
                    ),
                ),
                (
                    "sla_breached_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="SLA breached at"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_internal_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_internal_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_internal_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="employee",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internal_tickets",
                        to="users.usergroup",
                        verbose_name="group",
                    ),
                ),
            ],
            options={
                "verbose_name": "internal ticket",
                "verbose_name_plural": "internal tickets",
                "db_table": "crm_internal_tickets",
                "ordering": ["-created_at"],
            },
        ),
    ]
