# Generated by Django 5.1.15 on 2026-02-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalticket',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1 Star'), ('2', '2 Stars'), ('3', '3 Stars'), ('4', '4 Stars'), ('5', '5 Stars')], default='', max_length=1, verbose_name='rating'),
        ),
        migrations.AddField(
            model_name='internalticket',
            name='reopen_count',
            field=models.PositiveIntegerField(default=0, verbose_name='reopen count'),
        ),
        migrations.AddField(
            model_name='internalticket',
            name='satisfaction_survey_feedback',
            field=models.TextField(blank=True, default='', verbose_name='satisfaction survey feedback'),
        ),
    ]
