# Generated by Django 5.1.15 on 2026-02-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contacttag_contacttagassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='assistant_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='assistant phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='fax'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='home_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='home phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='office phone'),
        ),
    ]
