# Generated by Django 5.1.15 on 2026-02-27 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_corporation_data(apps, schema_editor):
    """
    Migrate existing corporation FK to the new M2M relationship and primary_corporation.
    """
    Contact = apps.get_model("contacts", "Contact")

    # For each contact with a corporation, set primary_corporation and add to M2M
    for contact in Contact.objects.filter(corporation__isnull=False):
        contact.primary_corporation = contact.corporation
        contact.save(update_fields=["primary_corporation"])
        contact.corporations.add(contact.corporation)


def reverse_migration(apps, schema_editor):
    """
    Reverse: copy primary_corporation back to corporation field.
    """
    Contact = apps.get_model("contacts", "Contact")

    for contact in Contact.objects.filter(primary_corporation__isnull=False):
        contact.corporation = contact.primary_corporation
        contact.save(update_fields=["corporation"])


class Migration(migrations.Migration):

    dependencies = [
        ("business_hours", "0001_initial"),
        ("contacts", "0009_contact_idx_contact_status_assigned_and_more"),
        ("corporations", "0009_add_multi_corporation_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add new fields while keeping old corporation field
        migrations.AddField(
            model_name="contact",
            name="corporations",
            field=models.ManyToManyField(
                blank=True,
                related_name="contacts_new",
                to="corporations.corporation",
                verbose_name="corporations",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="primary_corporation",
            field=models.ForeignKey(
                blank=True,
                help_text="Main corporation for this contact",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_contacts",
                to="corporations.corporation",
                verbose_name="primary corporation",
            ),
        ),
        # Step 2: Migrate data from old FK to new M2M and primary_corporation
        migrations.RunPython(migrate_corporation_data, reverse_migration),
        # Step 3: Remove old index and field
        migrations.RemoveIndex(
            model_name="contact",
            name="idx_contact_corp_status",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="corporation",
        ),
        # Step 4: Update the related_name for corporations M2M (now that old contacts is gone)
        migrations.AlterField(
            model_name="contact",
            name="corporations",
            field=models.ManyToManyField(
                blank=True,
                related_name="contacts",
                to="corporations.corporation",
                verbose_name="corporations",
            ),
        ),
        # Step 5: Add new index
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["primary_corporation", "status"],
                name="idx_contact_prim_corp_status",
            ),
        ),
    ]
