# Generated by Django 5.1.15 on 2026-02-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_add_multi_corporation_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='facebook_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedin_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='LinkedIn URL'),
        ),
    ]
