# Generated by Django 5.1.15 on 2026-02-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_asset_date_in_service_asset_date_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
