# Generated by Django 5.1.15 on 2026-02-21 19:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporations", "0005_increase_phone_field_length"),
        ("inventory", "0006_fix_field_lengths"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_number", models.CharField(db_index=True, max_length=50)),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("partial", "Partially Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("customer_address", models.TextField(blank=True, default="")),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "amount_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("terms_conditions", models.TextField(blank=True, default="")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_invoices",
                        to="corporations.corporation",
                    ),
                ),
            ],
            options={
                "db_table": "crm_tenant_invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("product_code", models.CharField(max_length=50)),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("unit", models.CharField(default="Units", max_length=50)),
                ("qty_in_stock", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("image_url", models.URLField(blank=True, default="")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_products",
                        to="corporations.corporation",
                    ),
                ),
            ],
            options={
                "db_table": "crm_tenant_products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TenantQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quote_number", models.CharField(db_index=True, max_length=50)),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("converted", "Converted to Invoice"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("customer_address", models.TextField(blank=True, default="")),
                ("quote_date", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("terms_conditions", models.TextField(blank=True, default="")),
                (
                    "converted_invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_quote",
                        to="inventory.tenantinvoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_quotes",
                        to="corporations.corporation",
                    ),
                ),
            ],
            options={
                "db_table": "crm_tenant_quotes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("service_code", models.CharField(max_length=50)),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("usage_unit", models.CharField(default="Hours", max_length=50)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_services",
                        to="corporations.corporation",
                    ),
                ),
            ],
            options={
                "db_table": "crm_tenant_services",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TenantQuoteLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_line_items",
                        to="inventory.tenantproduct",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="inventory.tenantquote",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_line_items",
                        to="inventory.tenantservice",
                    ),
                ),
            ],
            options={
                "db_table": "crm_tenant_quote_line_items",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="TenantInvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="inventory.tenantinvoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_line_items",
                        to="inventory.tenantproduct",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_line_items",
                        to="inventory.tenantservice",
                    ),
                ),
            ],
            options={
                "db_table": "crm_tenant_invoice_line_items",
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddConstraint(
            model_name="tenantinvoice",
            constraint=models.UniqueConstraint(
                fields=("tenant", "invoice_number"), name="unique_invoice_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantproduct",
            constraint=models.UniqueConstraint(
                fields=("tenant", "product_code"), name="unique_product_code_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantquote",
            constraint=models.UniqueConstraint(
                fields=("tenant", "quote_number"), name="unique_quote_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantservice",
            constraint=models.UniqueConstraint(
                fields=("tenant", "service_code"), name="unique_service_code_per_tenant"
            ),
        ),
    ]
