# Generated by Django 5.1.15 on 2026-02-14 19:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0005_add_color_field"),
        ("cases", "0004_sla_escalationrule_caseslastatus_slabreach"),
        ("contacts", "0007_contacttag_contacttagassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoProvider",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("zoom", "Zoom"),
                            ("google_meet", "Google Meet"),
                            ("teams", "Microsoft Teams"),
                            ("webex", "Cisco Webex"),
                            ("custom", "Custom"),
                        ],
                        default="zoom",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("client_id", models.CharField(blank=True, max_length=255)),
                ("client_secret", models.CharField(blank=True, max_length=255)),
                ("redirect_uri", models.URLField(blank=True)),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("api_secret", models.CharField(blank=True, max_length=255)),
                ("account_id", models.CharField(blank=True, max_length=255)),
                ("webhook_url", models.URLField(blank=True)),
                ("webhook_secret", models.CharField(blank=True, max_length=255)),
                ("default_duration", models.IntegerField(default=60)),
                ("auto_recording", models.BooleanField(default=False)),
                ("waiting_room_enabled", models.BooleanField(default=True)),
                ("require_password", models.BooleanField(default=True)),
                ("mute_on_entry", models.BooleanField(default=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Video Provider",
                "verbose_name_plural": "Video Providers",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="VideoMeeting",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("meeting_number", models.CharField(blank=True, max_length=50)),
                ("password", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("started", "Started"),
                            ("ended", "Ended"),
                            ("canceled", "Canceled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("instant", "Instant Meeting"),
                            ("scheduled", "Scheduled Meeting"),
                            ("recurring", "Recurring Meeting"),
                            ("personal", "Personal Room"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                ("duration", models.IntegerField(default=60)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("join_url", models.URLField(blank=True)),
                ("host_url", models.URLField(blank=True)),
                ("registration_url", models.URLField(blank=True)),
                ("waiting_room", models.BooleanField(default=True)),
                ("require_registration", models.BooleanField(default=False)),
                (
                    "auto_recording",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("local", "Local"),
                            ("cloud", "Cloud"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("mute_on_entry", models.BooleanField(default=True)),
                ("allow_screen_sharing", models.BooleanField(default=True)),
                ("recording_url", models.URLField(blank=True)),
                ("recording_duration", models.IntegerField(default=0)),
                ("recording_file_size", models.BigIntegerField(default=0)),
                ("transcription", models.TextField(blank=True)),
                ("participants_count", models.IntegerField(default=0)),
                ("provider_data", models.JSONField(blank=True, default=dict)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_meetings",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_meetings",
                        to="cases.taxcase",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_meetings",
                        to="contacts.contact",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_video_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="video_meetings.videoprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Meeting",
                "verbose_name_plural": "Video Meetings",
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="MeetingRecording",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recording_type",
                    models.CharField(
                        choices=[
                            ("shared_screen_speaker", "Shared Screen with Speaker"),
                            ("shared_screen_gallery", "Shared Screen with Gallery"),
                            ("speaker_view", "Speaker View"),
                            ("gallery_view", "Gallery View"),
                            ("audio_only", "Audio Only"),
                            ("chat", "Chat Transcript"),
                        ],
                        default="shared_screen_speaker",
                        max_length=30,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=100)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.BigIntegerField(default=0)),
                ("file_type", models.CharField(blank=True, max_length=20)),
                ("duration", models.IntegerField(default=0)),
                ("download_url", models.URLField(blank=True)),
                ("play_url", models.URLField(blank=True)),
                ("share_url", models.URLField(blank=True)),
                ("is_ready", models.BooleanField(default=False)),
                ("download_expires_at", models.DateTimeField(blank=True, null=True)),
                ("transcription", models.TextField(blank=True)),
                ("transcription_status", models.CharField(blank=True, max_length=20)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="video_meetings.videomeeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Recording",
                "verbose_name_plural": "Meeting Recordings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoMeetingSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("default_duration", models.IntegerField(default=60)),
                ("default_waiting_room", models.BooleanField(default=True)),
                ("default_mute_on_entry", models.BooleanField(default=True)),
                (
                    "default_auto_recording",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("local", "Local"),
                            ("cloud", "Cloud"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("auto_add_to_appointments", models.BooleanField(default=True)),
                ("send_calendar_invites", models.BooleanField(default=True)),
                ("send_reminder_emails", models.BooleanField(default=True)),
                ("reminder_minutes_before", models.IntegerField(default=15)),
                ("recording_retention_days", models.IntegerField(default=90)),
                ("auto_delete_recordings", models.BooleanField(default=False)),
                (
                    "default_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="video_meetings.videoprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Meeting Settings",
                "verbose_name_plural": "Video Meeting Settings",
            },
        ),
        migrations.CreateModel(
            name="UserVideoConnection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("provider_user_id", models.CharField(blank=True, max_length=255)),
                ("provider_email", models.EmailField(blank=True, max_length=254)),
                ("provider_name", models.CharField(blank=True, max_length=255)),
                ("personal_meeting_url", models.URLField(blank=True)),
                ("personal_meeting_id", models.CharField(blank=True, max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_connections",
                        to="video_meetings.videoprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Video Connection",
                "verbose_name_plural": "User Video Connections",
            },
        ),
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("host", "Host"),
                            ("co_host", "Co-host"),
                            ("participant", "Participant"),
                        ],
                        default="participant",
                        max_length=20,
                    ),
                ),
                (
                    "join_status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("registered", "Registered"),
                            ("joined", "Joined"),
                            ("left", "Left"),
                            ("no_show", "No Show"),
                        ],
                        default="invited",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("duration_in_meeting", models.IntegerField(default=0)),
                (
                    "provider_participant_id",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_participations",
                        to="contacts.contact",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="video_meetings.videomeeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Participant",
                "verbose_name_plural": "Meeting Participants",
                "unique_together": {("meeting", "email")},
            },
        ),
        migrations.AddIndex(
            model_name="videomeeting",
            index=models.Index(
                fields=["scheduled_start"], name="video_meeti_schedul_9b837c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videomeeting",
            index=models.Index(fields=["status"], name="video_meeti_status_c8490b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="uservideoconnection",
            unique_together={("user", "provider")},
        ),
    ]
