# Generated by Django 5.1.15 on 2026-02-14 18:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0007_contacttag_contacttagassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationSequence",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("signup", "New Signup/Contact"),
                            ("tag_added", "Tag Added"),
                            ("list_added", "Added to List"),
                            ("case_created", "Case Created"),
                            ("case_status", "Case Status Changed"),
                            ("date_field", "Date Field (Birthday, etc.)"),
                            ("manual", "Manual Enrollment"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                (
                    "trigger_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Trigger configuration (e.g., {'tag': 'new_client', 'list_id': 'xxx'})",
                    ),
                ),
                (
                    "from_name",
                    models.CharField(default="Ebenezer Tax Services", max_length=100),
                ),
                (
                    "from_email",
                    models.EmailField(default="info@ebenezertax.com", max_length=254),
                ),
                ("reply_to", models.EmailField(blank=True, max_length=254)),
                ("total_enrolled", models.IntegerField(default=0)),
                ("total_completed", models.IntegerField(default=0)),
                ("total_unsubscribed", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_automation_sequences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationStep",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("email", "Send Email"),
                            ("wait", "Wait"),
                            ("condition", "Condition/Branch"),
                            ("tag", "Add/Remove Tag"),
                            ("list", "Add/Remove from List"),
                            ("notify", "Notify Team"),
                            ("task", "Create Task"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("html_content", models.TextField(blank=True)),
                ("text_content", models.TextField(blank=True)),
                ("wait_days", models.IntegerField(default=0)),
                ("wait_hours", models.IntegerField(default=0)),
                ("wait_minutes", models.IntegerField(default=0)),
                ("condition_field", models.CharField(blank=True, max_length=100)),
                (
                    "condition_operator",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("equals", "Equals"),
                            ("not_equals", "Not Equals"),
                            ("contains", "Contains"),
                            ("opened", "Opened Previous Email"),
                            ("clicked", "Clicked Previous Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("condition_value", models.CharField(blank=True, max_length=200)),
                (
                    "tag_action",
                    models.CharField(
                        blank=True,
                        choices=[("add", "Add"), ("remove", "Remove")],
                        max_length=10,
                    ),
                ),
                ("tag_name", models.CharField(blank=True, max_length=100)),
                ("total_processed", models.IntegerField(default=0)),
                ("total_sent", models.IntegerField(default=0)),
                ("total_opened", models.IntegerField(default=0)),
                ("total_clicked", models.IntegerField(default=0)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="marketing.automationsequence",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "order"],
            },
        ),
        migrations.CreateModel(
            name="AutomationEnrollment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("unsubscribed", "Unsubscribed"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("next_step_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_enrollments",
                        to="contacts.contact",
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="marketing.automationsequence",
                    ),
                ),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_enrollments",
                        to="marketing.automationstep",
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_at"],
                "unique_together": {("sequence", "contact")},
            },
        ),
        migrations.CreateModel(
            name="AutomationStepLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("email_sent", models.BooleanField(default=False)),
                ("email_opened", models.BooleanField(default=False)),
                ("email_clicked", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_logs",
                        to="marketing.automationenrollment",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="marketing.automationstep",
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Campaign"),
                            ("automated", "Automated/Drip"),
                            ("ab_test", "A/B Test"),
                            ("rss", "RSS Feed"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                ("preview_text", models.CharField(blank=True, max_length=200)),
                (
                    "from_name",
                    models.CharField(default="Ebenezer Tax Services", max_length=100),
                ),
                (
                    "from_email",
                    models.EmailField(default="info@ebenezertax.com", max_length=254),
                ),
                ("reply_to", models.EmailField(blank=True, max_length=254)),
                ("html_content", models.TextField()),
                ("text_content", models.TextField(blank=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("track_opens", models.BooleanField(default=True)),
                ("track_clicks", models.BooleanField(default=True)),
                ("is_ab_test", models.BooleanField(default=False)),
                ("ab_test_subject_b", models.CharField(blank=True, max_length=500)),
                ("ab_test_content_b", models.TextField(blank=True)),
                (
                    "ab_test_split",
                    models.IntegerField(
                        default=50, help_text="Percentage for variant A"
                    ),
                ),
                (
                    "ab_test_winner_criteria",
                    models.CharField(
                        choices=[
                            ("open_rate", "Open Rate"),
                            ("click_rate", "Click Rate"),
                        ],
                        default="open_rate",
                        max_length=20,
                    ),
                ),
                ("total_recipients", models.IntegerField(default=0)),
                ("total_sent", models.IntegerField(default=0)),
                ("total_delivered", models.IntegerField(default=0)),
                ("total_opened", models.IntegerField(default=0)),
                ("total_clicked", models.IntegerField(default=0)),
                ("total_bounced", models.IntegerField(default=0)),
                ("total_unsubscribed", models.IntegerField(default=0)),
                ("total_complained", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_url", models.URLField(max_length=2000)),
                ("tracking_url", models.URLField(blank=True, max_length=2000)),
                ("total_clicks", models.IntegerField(default=0)),
                ("unique_clicks", models.IntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="marketing.campaign",
                    ),
                ),
            ],
            options={
                "unique_together": {("campaign", "original_url")},
            },
        ),
        migrations.CreateModel(
            name="CampaignRecipient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("unsubscribed", "Unsubscribed"),
                            ("complained", "Complained"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "ab_variant",
                    models.CharField(
                        blank=True, choices=[("A", "A"), ("B", "B")], max_length=1
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("bounced_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("open_count", models.IntegerField(default=0)),
                ("click_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "bounce_type",
                    models.CharField(
                        blank=True,
                        choices=[("hard", "Hard Bounce"), ("soft", "Soft Bounce")],
                        max_length=20,
                    ),
                ),
                ("tracking_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="marketing.campaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_emails",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("campaign", "contact")},
            },
        ),
        migrations.CreateModel(
            name="CampaignLinkClick",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="marketing.campaignlink",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_clicks",
                        to="marketing.campaignrecipient",
                    ),
                ),
            ],
            options={
                "ordering": ["-clicked_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("subject", models.CharField(max_length=500)),
                ("preview_text", models.CharField(blank=True, max_length=200)),
                ("html_content", models.TextField()),
                ("text_content", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("newsletter", "Newsletter"),
                            ("promotional", "Promotional"),
                            ("transactional", "Transactional"),
                            ("reminder", "Reminder"),
                            ("follow_up", "Follow Up"),
                            ("announcement", "Announcement"),
                            ("welcome", "Welcome"),
                            ("tax_season", "Tax Season"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_campaign_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="marketing.campaigntemplate",
            ),
        ),
        migrations.AddField(
            model_name="automationstep",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="marketing.campaigntemplate",
            ),
        ),
        migrations.CreateModel(
            name="EmailList",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_dynamic", models.BooleanField(default=False)),
                (
                    "filter_criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filter criteria for dynamic lists (e.g., {'status': 'active', 'tags': ['vip']})",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_email_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email List",
                "verbose_name_plural": "Email Lists",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="email_lists",
            field=models.ManyToManyField(
                blank=True, related_name="campaigns", to="marketing.emaillist"
            ),
        ),
        migrations.AddField(
            model_name="automationstep",
            name="target_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="automation_targets",
                to="marketing.emaillist",
            ),
        ),
        migrations.AddField(
            model_name="automationsequence",
            name="email_lists",
            field=models.ManyToManyField(
                blank=True,
                related_name="automation_sequences",
                to="marketing.emaillist",
            ),
        ),
        migrations.CreateModel(
            name="EmailListSubscriber",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_subscribed", models.BooleanField(default=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("import", "Import"),
                            ("webform", "Web Form"),
                            ("api", "API"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_subscriptions",
                        to="contacts.contact",
                    ),
                ),
                (
                    "email_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="marketing.emaillist",
                    ),
                ),
            ],
            options={
                "ordering": ["-subscribed_at"],
                "unique_together": {("email_list", "contact")},
            },
        ),
    ]
