# Generated by Django 5.1.15 on 2026-02-07 14:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0007_contacttag_contacttagassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ai_provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI (GPT)"),
                            ("anthropic", "Anthropic (Claude)"),
                        ],
                        default="openai",
                        max_length=20,
                        verbose_name="AI Provider",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Encrypted API key for the AI provider.",
                        max_length=500,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="gpt-4o-mini",
                        help_text="e.g., gpt-4o-mini, gpt-4o, claude-3-haiku-20240307",
                        max_length=100,
                        verbose_name="Model Name",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="Controls randomness. 0 = deterministic, 1 = creative.",
                        verbose_name="Temperature",
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Maximum tokens in AI response.",
                        verbose_name="Max Tokens",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        default="",
                        help_text="Instructions that define the chatbot's personality and behavior.",
                        verbose_name="System Prompt",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="Ebenezer Tax Services",
                        max_length=200,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "welcome_message",
                    models.TextField(
                        default="Hello! I'm the Ebenezer Tax Services assistant. How can I help you today?",
                        verbose_name="Welcome Message",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable or disable the chatbot.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "allow_appointments",
                    models.BooleanField(
                        default=True,
                        help_text="Allow the chatbot to book appointments.",
                        verbose_name="Allow Appointment Booking",
                    ),
                ),
                (
                    "handoff_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Allow transferring to a human representative.",
                        verbose_name="Enable Human Handoff",
                    ),
                ),
                (
                    "handoff_message",
                    models.TextField(
                        default="I'll connect you with a representative who can better assist you. Please hold on.",
                        verbose_name="Handoff Message",
                    ),
                ),
                (
                    "fallback_message",
                    models.TextField(
                        default="I'm sorry, I can only help with questions related to Ebenezer Tax Services. Would you like to speak with a representative?",
                        verbose_name="Fallback Message",
                    ),
                ),
                (
                    "max_fallbacks_before_handoff",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Number of off-topic responses before suggesting human handoff.",
                        verbose_name="Max Fallbacks Before Handoff",
                    ),
                ),
            ],
            options={
                "verbose_name": "chatbot configuration",
                "verbose_name_plural": "chatbot configurations",
                "db_table": "crm_chatbot_configuration",
            },
        ),
        migrations.CreateModel(
            name="ChatbotAppointmentSlot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Day of Week",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "slot_duration_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Slot Duration (minutes)"
                    ),
                ),
                (
                    "max_appointments",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Max Appointments per Slot"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chatbot_slots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "appointment slot",
                "verbose_name_plural": "appointment slots",
                "db_table": "crm_chatbot_appointment_slots",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ChatbotConversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("handed_off", "Handed Off to Human"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "fallback_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Fallback Count"
                    ),
                ),
                (
                    "handed_off_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Handed Off At"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Closed At"
                    ),
                ),
                (
                    "appointment_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores appointment booking progress.",
                        verbose_name="Appointment Context",
                    ),
                ),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chatbot_handoffs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned staff",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_conversations",
                        to="contacts.contact",
                        verbose_name="contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "chatbot conversation",
                "verbose_name_plural": "chatbot conversations",
                "db_table": "crm_chatbot_conversations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatbotKnowledgeEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("faq", "FAQ"),
                            ("service", "Service Description"),
                            ("policy", "Policy"),
                            ("general", "General Information"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Entry Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Topic or question title.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The information or answer for this topic.",
                        verbose_name="Content",
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Comma-separated keywords for better matching.",
                        verbose_name="Keywords",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Higher priority entries are shown first.",
                        verbose_name="Priority",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_entries",
                        to="chatbot.chatbotconfiguration",
                        verbose_name="configuration",
                    ),
                ),
            ],
            options={
                "verbose_name": "knowledge entry",
                "verbose_name_plural": "knowledge entries",
                "db_table": "crm_chatbot_knowledge",
                "ordering": ["-priority", "title"],
            },
        ),
        migrations.CreateModel(
            name="ChatbotMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("appointment_request", "Appointment Request"),
                            ("appointment_confirm", "Appointment Confirmation"),
                            ("handoff_request", "Handoff Request"),
                        ],
                        default="text",
                        max_length=30,
                        verbose_name="Message Type",
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data like appointment details.",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "tokens_used",
                    models.PositiveIntegerField(default=0, verbose_name="Tokens Used"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatbot.chatbotconversation",
                        verbose_name="conversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "chatbot message",
                "verbose_name_plural": "chatbot messages",
                "db_table": "crm_chatbot_messages",
                "ordering": ["created_at"],
            },
        ),
    ]
