# Generated by Django 5.1.15 on 2026-02-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_add_comment_email_and_department_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
