# Generated by Django 5.1.15 on 2026-02-04 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRMModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Machine name: contacts, cases, quotes, etc.', max_length=50, unique=True, verbose_name='name')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('label_plural', models.CharField(max_length=100, verbose_name='label plural')),
                ('icon', models.CharField(blank=True, default='', help_text='Lucide icon name for frontend.', max_length=50, verbose_name='icon')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort order')),
                ('number_prefix', models.CharField(blank=True, default='', help_text='e.g. TC, QT, CT', max_length=20, verbose_name='number prefix')),
                ('number_format', models.CharField(blank=True, default='', help_text='Pattern: {prefix}-{year}-{seq:04d}', max_length=50, verbose_name='number format')),
                ('number_reset_period', models.CharField(blank=True, default='yearly', help_text='yearly, monthly, or never', max_length=20, verbose_name='number reset period')),
                ('number_next_seq', models.PositiveIntegerField(default=1, verbose_name='next sequence number')),
                ('default_fields', models.JSONField(blank=True, default=dict, help_text='Core field visibility configuration.', verbose_name='default fields')),
            ],
            options={
                'verbose_name': 'CRM module',
                'verbose_name_plural': 'CRM modules',
                'db_table': 'crm_modules',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Picklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Machine name: case_status, quote_stage, etc.', max_length=100, verbose_name='name')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('is_system', models.BooleanField(default=False, help_text='Prevent deletion of system picklists.', verbose_name='system picklist')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('module', models.ForeignKey(blank=True, help_text='null = global picklist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picklists', to='module_config.crmmodule', verbose_name='module')),
            ],
            options={
                'verbose_name': 'picklist',
                'verbose_name_plural': 'picklists',
                'db_table': 'crm_picklists',
                'ordering': ['name'],
                'unique_together': {('module', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PicklistValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100, verbose_name='value')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort order')),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('color', models.CharField(blank=True, default='', help_text='CSS color for badges.', max_length=20, verbose_name='color')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('picklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='module_config.picklist', verbose_name='picklist')),
            ],
            options={
                'verbose_name': 'picklist value',
                'verbose_name_plural': 'picklist values',
                'db_table': 'crm_picklist_values',
                'ordering': ['sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(help_text='Machine name (slug).', max_length=100, verbose_name='field name')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date'), ('datetime', 'Date & Time'), ('boolean', 'Boolean'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL'), ('textarea', 'Text Area'), ('select', 'Select'), ('multiselect', 'Multi-Select')], max_length=20, verbose_name='field type')),
                ('is_required', models.BooleanField(default=False, verbose_name='required')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('default_value', models.CharField(blank=True, default='', max_length=500, verbose_name='default value')),
                ('placeholder', models.CharField(blank=True, default='', max_length=200, verbose_name='placeholder')),
                ('help_text', models.CharField(blank=True, default='', max_length=500, verbose_name='help text')),
                ('options', models.JSONField(blank=True, default=list, help_text='For select/multiselect: [{"value":"a","label":"A"}]', verbose_name='options')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='{"min":0,"max":100,"regex":"..."}', verbose_name='validation rules')),
                ('sort_order', models.IntegerField(default=0, verbose_name='sort order')),
                ('section', models.CharField(blank=True, default='', help_text='Group fields into sections.', max_length=100, verbose_name='section')),
                ('visible_to_roles', models.JSONField(blank=True, default=list, help_text='Empty = all roles, or list of role slugs.', verbose_name='visible to roles')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='module_config.crmmodule', verbose_name='module')),
            ],
            options={
                'verbose_name': 'custom field',
                'verbose_name_plural': 'custom fields',
                'db_table': 'crm_custom_fields',
                'ordering': ['sort_order', 'field_name'],
                'unique_together': {('module', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='FieldLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=100, verbose_name='field name')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='language')),
                ('custom_label', models.CharField(max_length=200, verbose_name='custom label')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_labels', to='module_config.crmmodule', verbose_name='module')),
            ],
            options={
                'verbose_name': 'field label',
                'verbose_name_plural': 'field labels',
                'db_table': 'crm_field_labels',
                'ordering': ['module', 'field_name'],
                'unique_together': {('module', 'field_name', 'language')},
            },
        ),
    ]
