# Generated by Django 5.1.15 on 2026-02-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_modulepermission_module_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_assign_records_to",
            field=models.CharField(
                choices=[
                    ("all_users_all_groups", "All Users & All Groups"),
                    (
                        "same_role_hierarchy",
                        "Same Role or Same Hierarchy or Subordinate Role & All Groups",
                    ),
                ],
                default="all_users_all_groups",
                max_length=30,
                verbose_name="can assign records to",
            ),
        ),
    ]
