# Generated by Django 5.1.15 on 2026-02-15 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


def clear_department_field(apps, schema_editor):
    """
    Clear the old department CharField values before converting to ForeignKey.
    The old department was a text field - we need to clear it before the schema change.
    """
    User = apps.get_model("users", "User")
    # Set all department values to empty string (will become NULL after field change)
    User.objects.all().update(department="")


def reverse_clear(apps, schema_editor):
    """Reverse migration - nothing to do."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_add_2fa_role_enforcement"),
    ]

    operations = [
        # Step 1: Create the Department model
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="code"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex color code for UI display",
                        max_length=7,
                        verbose_name="color",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Lucide icon name for UI display",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which departments appear in lists",
                        verbose_name="display order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "department",
                "verbose_name_plural": "departments",
                "db_table": "crm_departments",
                "ordering": ["order", "name"],
            },
        ),
        # Step 2: Remove the old department CharField
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
        # Step 3: Add the new department ForeignKey
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.department",
                verbose_name="department",
            ),
        ),
    ]
