# Generated by Django 5.1.15 on 2026-02-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_department_alter_user_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="phone"
            ),
        ),
    ]
