# Generated by Django 5.1.15 on 2026-02-03 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("contacts", "0001_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="account name")),
                (
                    "email_address",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "imap_host",
                    models.CharField(max_length=255, verbose_name="IMAP host"),
                ),
                (
                    "imap_port",
                    models.PositiveIntegerField(default=993, verbose_name="IMAP port"),
                ),
                (
                    "imap_use_ssl",
                    models.BooleanField(default=True, verbose_name="IMAP use SSL"),
                ),
                (
                    "smtp_host",
                    models.CharField(max_length=255, verbose_name="SMTP host"),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(default=587, verbose_name="SMTP port"),
                ),
                (
                    "smtp_use_tls",
                    models.BooleanField(default=True, verbose_name="SMTP use TLS"),
                ),
                ("username", models.CharField(max_length=255, verbose_name="username")),
                ("password", models.CharField(max_length=255, verbose_name="password")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last sync"
                    ),
                ),
                (
                    "sync_interval_minutes",
                    models.PositiveIntegerField(
                        default=5, verbose_name="sync interval (minutes)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "email account",
                "verbose_name_plural": "email accounts",
                "db_table": "crm_email_accounts",
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message_id",
                    models.CharField(
                        db_index=True,
                        max_length=500,
                        unique=True,
                        verbose_name="Message-ID header",
                    ),
                ),
                (
                    "in_reply_to",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="In-Reply-To header",
                    ),
                ),
                (
                    "references",
                    models.TextField(
                        blank=True, default="", verbose_name="References header"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        db_index=True,
                        max_length=10,
                        verbose_name="direction",
                    ),
                ),
                (
                    "from_address",
                    models.EmailField(max_length=254, verbose_name="from"),
                ),
                ("to_addresses", models.JSONField(default=list, verbose_name="to")),
                (
                    "cc_addresses",
                    models.JSONField(blank=True, default=list, verbose_name="cc"),
                ),
                (
                    "bcc_addresses",
                    models.JSONField(blank=True, default=list, verbose_name="bcc"),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="subject"
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        blank=True, default="", verbose_name="body (plain text)"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="sent at"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="read")),
                (
                    "is_starred",
                    models.BooleanField(default=False, verbose_name="starred"),
                ),
                (
                    "folder",
                    models.CharField(
                        choices=[
                            ("inbox", "Inbox"),
                            ("sent", "Sent"),
                            ("drafts", "Drafts"),
                            ("trash", "Trash"),
                        ],
                        db_index=True,
                        default="inbox",
                        max_length=20,
                        verbose_name="folder",
                    ),
                ),
                (
                    "imap_uid",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="IMAP UID"
                    ),
                ),
                (
                    "raw_headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="raw headers"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="emails.emailaccount",
                        verbose_name="account",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_emails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="cases.taxcase",
                        verbose_name="case",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="contacts.contact",
                        verbose_name="contact",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_emails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sent by",
                    ),
                ),
            ],
            options={
                "verbose_name": "email message",
                "verbose_name_plural": "email messages",
                "db_table": "crm_email_messages",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="email_attachments/%Y/%m/", verbose_name="file"
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="filename")),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="MIME type"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="file size (bytes)"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_attachments",
                        to="documents.document",
                        verbose_name="linked document",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="emails.emailmessage",
                        verbose_name="email",
                    ),
                ),
            ],
            options={
                "verbose_name": "email attachment",
                "verbose_name_plural": "email attachments",
                "db_table": "crm_email_attachments",
            },
        ),
        migrations.CreateModel(
            name="EmailSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error")],
                        db_index=True,
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "messages_fetched",
                    models.PositiveIntegerField(
                        default=0, verbose_name="messages fetched"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", verbose_name="error message"
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="started at")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="emails.emailaccount",
                        verbose_name="account",
                    ),
                ),
            ],
            options={
                "verbose_name": "email sync log",
                "verbose_name_plural": "email sync logs",
                "db_table": "crm_email_sync_logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="template name"
                    ),
                ),
                ("subject", models.CharField(max_length=500, verbose_name="subject")),
                ("body_text", models.TextField(verbose_name="body (plain text)")),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of placeholder variable names, e.g. ['contact_name', 'case_number']",
                        verbose_name="available variables",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "email template",
                "verbose_name_plural": "email templates",
                "db_table": "crm_email_templates",
            },
        ),
        migrations.CreateModel(
            name="EmailThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="subject"
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last message at"
                    ),
                ),
                (
                    "message_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="message count"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="archived"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_threads",
                        to="cases.taxcase",
                        verbose_name="case",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_threads",
                        to="contacts.contact",
                        verbose_name="contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "email thread",
                "verbose_name_plural": "email threads",
                "db_table": "crm_email_threads",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="emails.emailthread",
                verbose_name="thread",
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["account", "folder", "-sent_at"],
                name="crm_email_m_account_bc233b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["contact", "-sent_at"], name="crm_email_m_contact_2a86b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["case", "-sent_at"], name="crm_email_m_case_id_3145c8_idx"
            ),
        ),
    ]
