# Generated by Django 5.1.15 on 2026-02-14 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(max_length=280, unique=True, verbose_name="slug"),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Brief summary for search results and previews",
                        max_length=500,
                        verbose_name="summary",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public - Visible to all"),
                            ("internal", "Internal - Staff only"),
                            ("portal", "Portal - Logged-in users only"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="visibility",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="tags"),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Comma-separated keywords for search",
                        verbose_name="keywords",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="view count"),
                ),
                (
                    "helpful_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="helpful count"
                    ),
                ),
                (
                    "not_helpful_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="not helpful count"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="featured"),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="pinned"),
                ),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="allow comments"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="published at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expires at"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kb_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_kb_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="last edited by",
                    ),
                ),
                (
                    "related_articles",
                    models.ManyToManyField(
                        blank=True,
                        to="knowledge_base.article",
                        verbose_name="related articles",
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
                "db_table": "kb_articles",
                "ordering": ["-is_pinned", "-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="kb/attachments/%Y/%m/", verbose_name="file"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="file size"),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME type"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="knowledge_base.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "attachment",
                "verbose_name_plural": "attachments",
                "db_table": "kb_article_attachments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ArticleView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="session key"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="user agent"),
                ),
                (
                    "referrer",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="referrer"
                    ),
                ),
                (
                    "search_query",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Search query that led to this article",
                        max_length=255,
                        verbose_name="search query",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="knowledge_base.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "article view",
                "verbose_name_plural": "article views",
                "db_table": "kb_article_views",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="icon"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="#3b82f6",
                        max_length=20,
                        verbose_name="color",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Public categories are visible in the customer portal",
                        verbose_name="public",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="knowledge_base.category",
                        verbose_name="parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "db_table": "kb_categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="knowledge_base.category",
                verbose_name="category",
            ),
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=500, verbose_name="question")),
                ("answer", models.TextField(verbose_name="answer")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("is_public", models.BooleanField(default=True, verbose_name="public")),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="view count"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faqs",
                        to="knowledge_base.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_faqs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "db_table": "kb_faqs",
                "ordering": ["category", "order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="session key"
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("helpful", "Helpful"),
                            ("not_helpful", "Not Helpful"),
                        ],
                        max_length=20,
                        verbose_name="feedback type",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="comment"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="email"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="knowledge_base.article",
                        verbose_name="article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "article feedback",
                "verbose_name_plural": "article feedback",
                "db_table": "kb_article_feedback",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("article", "user"),
                        name="unique_user_feedback",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "visibility"], name="kb_articles_status_ac9cde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category", "status"], name="kb_articles_categor_adfce6_idx"
            ),
        ),
    ]
