# Generated by Django 5.1.15 on 2026-02-22 03:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corporations", "0005_increase_phone_field_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this backup",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("global", "Global Backup"),
                            ("tenant", "Tenant Backup"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="backup type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path to the encrypted backup file",
                        max_length=500,
                        verbose_name="file path",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True,
                        help_text="File size in bytes",
                        null=True,
                        verbose_name="file size",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 checksum for integrity verification",
                        max_length=64,
                        verbose_name="checksum",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Celery task ID for tracking async operations",
                        max_length=50,
                        verbose_name="Celery task ID",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if backup/restore failed",
                        verbose_name="error message",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "include_media",
                    models.BooleanField(
                        default=True,
                        help_text="Include media files in backup",
                        verbose_name="include media",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Corporation for tenant-specific backups",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backups",
                        to="corporations.corporation",
                        verbose_name="corporation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_backups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "backup",
                "verbose_name_plural": "backups",
                "db_table": "crm_backups",
                "ordering": ["-created_at"],
            },
        ),
    ]
