# Generated by Django 5.1.15 on 2026-02-04 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_remove_role_can_assign_records_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('module', models.CharField(choices=[('cases', 'Cases'), ('contacts', 'Contacts'), ('corporations', 'Corporations'), ('quotes', 'Quotes'), ('tasks', 'Tasks'), ('documents', 'Documents'), ('appointments', 'Appointments'), ('internal_tickets', 'Internal Tickets')], db_index=True, max_length=30, verbose_name='module')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('trigger', models.CharField(choices=[('on_save', 'On Save'), ('via_process', 'Via Process')], default='on_save', max_length=20, verbose_name='trigger')),
                ('entry_criteria_all', models.JSONField(blank=True, default=list, help_text='All conditions must be met.', verbose_name='all conditions')),
                ('entry_criteria_any', models.JSONField(blank=True, default=list, help_text='At least one condition must be met.', verbose_name='any conditions')),
                ('apply_on', models.CharField(choices=[('created_by', 'Created By'), ('assigned_to', 'Assigned To')], default='assigned_to', max_length=20, verbose_name='apply rules on')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_approvals', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'approval',
                'verbose_name_plural': 'approvals',
                'db_table': 'crm_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(choices=[('approval', 'Final Approval'), ('rejection', 'Final Rejection')], db_index=True, max_length=10, verbose_name='phase')),
                ('action_type', models.CharField(choices=[('update_field', 'Update Field'), ('send_email', 'Send Email'), ('send_notification', 'Send Notification'), ('create_task', 'Create Task')], max_length=30, verbose_name='action type')),
                ('action_title', models.CharField(max_length=255, verbose_name='action title')),
                ('action_config', models.JSONField(blank=True, default=dict, verbose_name='action config')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approval', verbose_name='approval')),
            ],
            options={
                'verbose_name': 'approval action',
                'verbose_name_plural': 'approval actions',
                'db_table': 'crm_approval_actions',
                'ordering': ['phase', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_number', models.PositiveSmallIntegerField(default=1, verbose_name='rule number')),
                ('conditions', models.JSONField(blank=True, default=list, help_text='Conditions for this rule to match.', verbose_name='conditions')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='approvals.approval', verbose_name='approval')),
                ('approvers', models.ManyToManyField(blank=True, related_name='approval_rules', to=settings.AUTH_USER_MODEL, verbose_name='approvers')),
                ('owner_profiles', models.ManyToManyField(blank=True, related_name='approval_rules', to='users.role', verbose_name='owner profiles')),
            ],
            options={
                'verbose_name': 'approval rule',
                'verbose_name_plural': 'approval rules',
                'db_table': 'crm_approval_rules',
                'ordering': ['rule_number'],
            },
        ),
    ]
