# Generated by Django 5.1.15 on 2026-02-06 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webforms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webform",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Webform",
                "verbose_name_plural": "Webforms",
            },
        ),
        migrations.AlterModelOptions(
            name="webformfield",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Webform Field",
                "verbose_name_plural": "Webform Fields",
            },
        ),
        migrations.AlterModelOptions(
            name="webformhiddenfield",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Webform Hidden Field",
                "verbose_name_plural": "Webform Hidden Fields",
            },
        ),
        migrations.AlterModelOptions(
            name="webformroundrobinuser",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Round Robin User",
                "verbose_name_plural": "Round Robin Users",
            },
        ),
        migrations.AlterField(
            model_name="webform",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Default user to assign created records to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_webforms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned To",
            ),
        ),
        migrations.AlterField(
            model_name="webform",
            name="captcha_enabled",
            field=models.BooleanField(default=False, verbose_name="Captcha Enabled"),
        ),
        migrations.AlterField(
            model_name="webform",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_webforms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="webform",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="webform",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="webform",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="webform",
            name="primary_module",
            field=models.CharField(
                help_text="CRM module to create records in (e.g., contacts, cases, corporations)",
                max_length=50,
                verbose_name="Primary Module",
            ),
        ),
        migrations.AlterField(
            model_name="webform",
            name="return_url",
            field=models.URLField(
                blank=True,
                help_text="URL to redirect after form submission",
                max_length=2048,
                verbose_name="Return URL",
            ),
        ),
        migrations.AlterField(
            model_name="webform",
            name="round_robin_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Distribute assignments among round robin users",
                verbose_name="Round Robin Enabled",
            ),
        ),
        migrations.AlterField(
            model_name="webformfield",
            name="duplicate_handling",
            field=models.CharField(
                choices=[("none", "None"), ("skip", "Skip"), ("update", "Update")],
                default="none",
                max_length=20,
                verbose_name="Duplicate Handling",
            ),
        ),
        migrations.AlterField(
            model_name="webformfield",
            name="field_name",
            field=models.CharField(
                help_text="CRM field machine name",
                max_length=100,
                verbose_name="Field Name",
            ),
        ),
        migrations.AlterField(
            model_name="webformfield",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden"),
        ),
        migrations.AlterField(
            model_name="webformfield",
            name="is_mandatory",
            field=models.BooleanField(default=False, verbose_name="Mandatory"),
        ),
        migrations.AlterField(
            model_name="webformfield",
            name="override_value",
            field=models.CharField(
                blank=True,
                help_text="Default or forced value for this field",
                max_length=500,
                verbose_name="Override Value",
            ),
        ),
        migrations.AlterField(
            model_name="webformfield",
            name="reference_field",
            field=models.CharField(
                blank=True,
                help_text="For lookup reference fields",
                max_length=100,
                verbose_name="Reference Field",
            ),
        ),
        migrations.AlterField(
            model_name="webformfield",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="Sort Order"),
        ),
        migrations.AlterField(
            model_name="webformfield",
            name="webform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="webforms.webform",
                verbose_name="Webform",
            ),
        ),
        migrations.AlterField(
            model_name="webformhiddenfield",
            name="field_name",
            field=models.CharField(max_length=100, verbose_name="Field Name"),
        ),
        migrations.AlterField(
            model_name="webformhiddenfield",
            name="override_value",
            field=models.CharField(
                blank=True,
                help_text="Static value to use if URL parameter is not provided",
                max_length=500,
                verbose_name="Override Value",
            ),
        ),
        migrations.AlterField(
            model_name="webformhiddenfield",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="Sort Order"),
        ),
        migrations.AlterField(
            model_name="webformhiddenfield",
            name="url_parameter",
            field=models.CharField(
                blank=True,
                help_text="URL query parameter to read value from",
                max_length=100,
                verbose_name="URL Parameter",
            ),
        ),
        migrations.AlterField(
            model_name="webformhiddenfield",
            name="webform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hidden_fields",
                to="webforms.webform",
                verbose_name="Webform",
            ),
        ),
        migrations.AlterField(
            model_name="webformroundrobinuser",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="Sort Order"),
        ),
        migrations.AlterField(
            model_name="webformroundrobinuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="webformroundrobinuser",
            name="webform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_robin_users",
                to="webforms.webform",
                verbose_name="Webform",
            ),
        ),
    ]
