# Generated by Django 5.1.15 on 2026-02-03 20:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("cases_by_status", "Cases by Status"),
                            ("revenue_pipeline", "Revenue Pipeline"),
                            ("upcoming_deadlines", "Upcoming Deadlines"),
                            ("recent_cases", "Recent Cases"),
                            ("cases_by_preparer", "Cases by Preparer"),
                            ("cases_by_type", "Cases by Type"),
                            ("monthly_filings", "Monthly Filings"),
                            ("contact_stats", "Contact Stats"),
                            ("appointments_today", "Appointments Today"),
                            ("missing_docs", "Missing Documents"),
                            ("tasks_by_user", "Tasks by User"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="widget type",
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar Chart"),
                            ("pie", "Pie Chart"),
                            ("line", "Line Chart"),
                            ("area", "Area Chart"),
                            ("table", "Table"),
                            ("stat_card", "Stat Card"),
                        ],
                        max_length=20,
                        verbose_name="chart type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "default_enabled",
                    models.BooleanField(
                        default=True, verbose_name="enabled by default"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
            ],
            options={
                "verbose_name": "dashboard widget",
                "verbose_name_plural": "dashboard widgets",
                "db_table": "crm_dashboard_widgets",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark")],
                        default="light",
                        max_length=10,
                        verbose_name="theme",
                    ),
                ),
                (
                    "sidebar_collapsed",
                    models.BooleanField(
                        default=False, verbose_name="sidebar collapsed"
                    ),
                ),
                (
                    "items_per_page",
                    models.PositiveIntegerField(
                        default=25, verbose_name="items per page"
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="MM/DD/YYYY", max_length=20, verbose_name="date format"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/New_York",
                        max_length=50,
                        verbose_name="timezone",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user preference",
                "verbose_name_plural": "user preferences",
                "db_table": "crm_user_preferences",
            },
        ),
        migrations.CreateModel(
            name="UserDashboardConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="visible"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="position"),
                ),
                (
                    "width",
                    models.CharField(
                        choices=[
                            ("full", "Full Width"),
                            ("half", "Half Width"),
                            ("third", "One Third Width"),
                        ],
                        default="half",
                        max_length=10,
                        verbose_name="width",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_configs",
                        to="dashboard.dashboardwidget",
                        verbose_name="widget",
                    ),
                ),
            ],
            options={
                "verbose_name": "user dashboard config",
                "verbose_name_plural": "user dashboard configs",
                "db_table": "crm_user_dashboard_configs",
                "ordering": ["position"],
                "unique_together": {("user", "widget")},
            },
        ),
    ]
