# Generated by Django 5.1.15 on 2026-02-14 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StickyNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="title"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The note content/reminder text",
                        verbose_name="content",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("yellow", "Yellow"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("pink", "Pink"),
                            ("purple", "Purple"),
                            ("orange", "Orange"),
                        ],
                        default="yellow",
                        max_length=10,
                        verbose_name="color",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Pinned notes appear at the top",
                        verbose_name="pinned",
                    ),
                ),
                (
                    "reminder_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional date/time for reminder",
                        null=True,
                        verbose_name="reminder date",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="completed"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which notes appear",
                        verbose_name="position",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sticky_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "sticky note",
                "verbose_name_plural": "sticky notes",
                "db_table": "crm_sticky_notes",
                "ordering": ["-is_pinned", "position", "-created_at"],
            },
        ),
    ]
