# Generated by Django 5.1.15 on 2026-02-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_sticky_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StickyNote',
        ),
    ]
