# Generated by Django 5.1.15 on 2026-02-03 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('contacts', '0001_initial'),
        ('corporations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='file')),
                ('doc_type', models.CharField(choices=[('w2', 'W-2'), ('1099', '1099'), ('tax_return', 'Tax Return'), ('id_document', 'ID Document'), ('bank_statement', 'Bank Statement'), ('authorization', 'Authorization'), ('correspondence', 'Correspondence'), ('receipt', 'Receipt'), ('other', 'Other')], db_index=True, default='other', max_length=20, verbose_name='document type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='file size (bytes)')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='MIME type')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='encrypted')),
                ('encryption_key_id', models.CharField(blank=True, default='', help_text='Identifier for the encryption key used.', max_length=64, verbose_name='encryption key ID')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.taxcase', verbose_name='case')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contacts.contact', verbose_name='contact')),
                ('corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='corporations.corporation', verbose_name='corporation')),
                ('parent_document', models.ForeignKey(blank=True, help_text='Previous version of this document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documents.document', verbose_name='parent document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'db_table': 'crm_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download')], max_length=10, verbose_name='action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='user agent')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document', verbose_name='document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'document access log',
                'verbose_name_plural': 'document access logs',
                'db_table': 'crm_document_access_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
