# Generated by Django 5.1.15 on 2026-02-15 13:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0007_contacttag_contacttagassignment"),
        ("corporations", "0004_add_account_number"),
        ("documents", "0003_documentdownloadtoken"),
        ("users", "0013_department_alter_user_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentClientFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Default folders are created automatically and cannot be deleted.",
                        verbose_name="default folder",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_folders",
                        to="contacts.contact",
                        verbose_name="contact",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_folders",
                        to="corporations.corporation",
                        verbose_name="corporation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_department_folders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_folders",
                        to="users.department",
                        verbose_name="department",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="documents.departmentclientfolder",
                        verbose_name="parent folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "department client folder",
                "verbose_name_plural": "department client folders",
                "db_table": "crm_department_client_folders",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="department_folder",
            field=models.ForeignKey(
                blank=True,
                help_text="Department-specific folder for this document.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.departmentclientfolder",
                verbose_name="department folder",
            ),
        ),
        migrations.AddConstraint(
            model_name="departmentclientfolder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("contact__isnull", False), ("corporation__isnull", True)),
                    models.Q(("contact__isnull", True), ("corporation__isnull", False)),
                    _connector="OR",
                ),
                name="folder_linked_to_one_client_type",
            ),
        ),
    ]
