# Generated by Django 5.1.15 on 2026-02-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('workflow_triggered', 'Workflow Triggered'), ('case_status_changed', 'Case Status Changed'), ('email_assigned', 'Email Assigned'), ('email_no_reply', 'Email No Reply'), ('appointment_reminder', 'Appointment Reminder'), ('task_overdue', 'Task Overdue'), ('document_missing', 'Document Missing'), ('case_due_date', 'Case Due Date'), ('mention', 'Mentioned in Comment'), ('comment_reply', 'Reply to Comment'), ('system', 'System')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('workflow_triggered', 'Workflow Triggered'), ('case_status_changed', 'Case Status Changed'), ('email_assigned', 'Email Assigned'), ('email_no_reply', 'Email No Reply'), ('appointment_reminder', 'Appointment Reminder'), ('task_overdue', 'Task Overdue'), ('document_missing', 'Document Missing'), ('case_due_date', 'Case Due Date'), ('mention', 'Mentioned in Comment'), ('comment_reply', 'Reply to Comment'), ('system', 'System')], max_length=30),
        ),
    ]
