# Generated by Django 5.1.15 on 2026-02-14 19:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0005_add_color_field"),
        ("cases", "0004_sla_escalationrule_caseslastatus_slabreach"),
        ("contacts", "0007_contacttag_contacttagassignment"),
        ("corporations", "0003_add_vtiger_organization_fields"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playbook",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "playbook_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales Process"),
                            ("onboarding", "Client Onboarding"),
                            ("support", "Support Process"),
                            ("renewal", "Renewal Process"),
                            ("upsell", "Upsell/Cross-sell"),
                            ("collection", "Collection Process"),
                            ("custom", "Custom"),
                        ],
                        default="sales",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("case_stage", "Case Stage Change"),
                            ("contact_created", "Contact Created"),
                            ("quote_created", "Quote Created"),
                            ("appointment_scheduled", "Appointment Scheduled"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("trigger_conditions", models.JSONField(blank=True, default=dict)),
                ("applies_to_contacts", models.BooleanField(default=True)),
                ("applies_to_cases", models.BooleanField(default=True)),
                ("applies_to_corporations", models.BooleanField(default=False)),
                ("target_completion_days", models.IntegerField(blank=True, null=True)),
                ("success_criteria", models.TextField(blank=True)),
                ("times_started", models.IntegerField(default=0)),
                ("times_completed", models.IntegerField(default=0)),
                ("avg_completion_time", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_playbooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Playbook",
                "verbose_name_plural": "Playbooks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlaybookStep",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("task", "Create Task"),
                            ("email", "Send Email"),
                            ("call", "Make Call"),
                            ("meeting", "Schedule Meeting"),
                            ("note", "Add Note"),
                            ("update_field", "Update Field"),
                            ("wait", "Wait/Delay"),
                            ("decision", "Decision Point"),
                            ("checklist", "Checklist"),
                        ],
                        default="task",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("wait_duration", models.IntegerField(blank=True, null=True)),
                (
                    "wait_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hours", "Hours"),
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                        ],
                        default="days",
                        max_length=10,
                    ),
                ),
                ("condition", models.JSONField(blank=True, default=dict)),
                ("reminder_days", models.IntegerField(blank=True, null=True)),
                ("escalate_after_days", models.IntegerField(blank=True, null=True)),
                (
                    "next_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_steps",
                        to="playbooks.playbookstep",
                    ),
                ),
                (
                    "playbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="playbooks.playbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Playbook Step",
                "verbose_name_plural": "Playbook Steps",
                "ordering": ["playbook", "order"],
                "unique_together": {("playbook", "order")},
            },
        ),
        migrations.CreateModel(
            name="PlaybookExecution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                            ("failed", "Failed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("steps_completed", models.IntegerField(default=0)),
                ("total_steps", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("target_completion_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("outcome", models.CharField(blank=True, max_length=100)),
                ("outcome_notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_playbook_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook_executions",
                        to="cases.taxcase",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook_executions",
                        to="contacts.contact",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook_executions",
                        to="corporations.corporation",
                    ),
                ),
                (
                    "playbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="playbooks.playbook",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_playbook_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_executions",
                        to="playbooks.playbookstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Playbook Execution",
                "verbose_name_plural": "Playbook Executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PlaybookTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tax_services", "Tax Services"),
                            ("sales", "Sales"),
                            ("onboarding", "Onboarding"),
                            ("support", "Support"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("playbook_data", models.JSONField(default=dict)),
                ("times_used", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0)),
                ("rating_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_playbook_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Playbook Template",
                "verbose_name_plural": "Playbook Templates",
                "ordering": ["-times_used", "name"],
            },
        ),
        migrations.CreateModel(
            name="PlaybookStepExecution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("escalated", models.BooleanField(default=False)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_step_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_step_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="playbook_step_executions",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "created_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="playbook_step_executions",
                        to="tasks.task",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_executions",
                        to="playbooks.playbookexecution",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="playbooks.playbookstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Step Execution",
                "verbose_name_plural": "Step Executions",
                "ordering": ["step__order"],
                "unique_together": {("execution", "step")},
            },
        ),
    ]
